### ISSUE TITLE
Only version 2.7 working (All devices unavailable with all other versions)

### ISSUE THREAD

**Issue by rEd2k** [pyalarmdotcom/alarmdotcom#136]
This seems to be an issue from the recent fix implemented to correct unavailable devices. Since the fix, I now can only see my devices from ver. 2.7 or lower. There is also an an error connecting to Alarm.com services reported in the integrations (devices and sevices) menu from ver. 2.8 and up which seems to be the root cause. Any ideas? Thanks.

Edit: Forgot to mention the error states "Retrying setup: Error communicationg with api". I will upload a log and pics later when I get the chance ;)

**Comment by elahd** [comment]
Are you able to provide more detail? A screenshot or copy of the logs would be helpful.

**Comment by rEd2k** [comment]
Forgot to mention an error states "Retrying setup: Error communicationg with api". I will upload a log later when I get the chance ;)

**Comment by rEd2k** [comment]
![Devices](https://user-images.githubusercontent.com/24519343/175210499-eec1a463-ec37-4834-842b-b3bebf05497c.jpg)
![Unavailable](https://user-images.githubusercontent.com/24519343/175210514-28c450e2-b6f3-472b-a09d-75680a0f5747.jpg)
![Log1](https://user-images.githubusercontent.com/24519343/175210526-0a171eb8-9994-4db4-b0c5-3504ddbb76cc.jpg)

Here is a full log I copied from Supervisor as well (was all in green coloring). Please let me know of any other logs you may require:

22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-06-22 20:14:27 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-06-22 20:14:49 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-06-22 20:15:19 INFO (MainThread) [supervisor.host.info] Updating local host information
22-06-22 20:15:19 INFO (MainThread) [supervisor.host.services] Updating service information
22-06-22 20:15:19 INFO (MainThread) [supervisor.host.network] Updating local network information
22-06-22 20:15:19 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-06-22 20:15:19 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-06-22 20:16:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-06-22 20:46:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-06-22 21:14:27 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-06-22 21:16:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-06-22 21:46:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-06-22 22:14:28 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-06-22 22:14:49 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-06-22 22:15:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-06-22 22:15:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-06-22 22:15:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/Apipa169/Assistant-Relay-for-Hassio repository
22-06-22 22:15:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-06-22 22:15:42 INFO (MainThread) [supervisor.store] Loading add-ons from store: 67 all - 0 new - 0 remove
22-06-22 22:15:42 INFO (MainThread) [supervisor.store] Loading add-ons from store: 67 all - 0 new - 0 remove
22-06-22 22:16:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-06-22 22:21:56 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant
22-06-22 22:21:59 INFO (MainThread) [supervisor.host.info] Updating local host information
22-06-22 22:21:59 INFO (MainThread) [supervisor.host.services] Updating service information
22-06-22 22:21:59 INFO (MainThread) [supervisor.host.network] Updating local network information
22-06-22 22:21:59 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-06-22 22:21:59 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-06-22 22:22:11 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-06-22 22:22:13 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-06-22 22:22:13 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-06-22 22:22:14 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-06-22 22:22:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-06-22 22:22:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-06-22 22:22:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-06-22 22:22:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/Apipa169/Assistant-Relay-for-Hassio repository
22-06-22 22:22:15 INFO (MainThread) [supervisor.store] Loading add-ons from store: 67 all - 0 new - 0 remove
22-06-22 22:22:15 INFO (MainThread) [supervisor.store] Loading add-ons from store: 67 all - 0 new - 0 remove
22-06-22 22:22:31 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance

**Comment by jonlucas81** [comment]
i had the same issue. i was able to fix it. i had to go to the custom components folder in HA and rename/remove the alarmdotcom folder and reinstall... after doing this i removed the integration and readded it into HA...

**Comment by rEd2k** [comment]
> i had the same issue. i was able to fix it. i had to go to the custom components folder in HA and rename/remove the alarmdotcom folder and reinstall... after doing this i removed the integration and readded it into HA...

Thank you for trying to help. I did exactly what you suggested, but I still can't get it to work! I am at a loss here... Only version 2.7 seems to work fine.

**Comment by jonlucas81** [comment]
> Thank you for trying to help, I really appreciate it. I did exactly what you suggested, but I still can't get it to work! I am at a loss here... Only version 2.7 seems to work fine. I still get the "Retrying setup: Error communicating with api." Login and authentication works when adding the integration, but it doesn't want to allow any devices to show up and function.

so what i did was uninstalled the repository from hacs, rebooted, removed the integration, rebooted, renamed the folder using SMB, then reinstalled everything in order rebooting at each step... i never removed anything from lovelace or automations or anything like that.

**Comment by rEd2k** [comment]
> > Thank you for trying to help, I really appreciate it. I did exactly what you suggested, but I still can't get it to work! I am at a loss here... Only version 2.7 seems to work fine. I still get the "Retrying setup: Error communicating with api." Login and authentication works when adding the integration, but it doesn't want to allow any devices to show up and function.
> 
> so what i did was uninstalled the repository from hacs, rebooted, removed the integration, rebooted, renamed the folder using SMB, then reinstalled everything in order rebooting at each step... i never removed anything from lovelace or automations or anything like that.

        I have tried what you suggested, I tried it in every combination, I think I have exhausted my options at this point. I really do appreciate your help though. One thing I noticed is that before, the folder that needed renaming/deleting did always stick around when I did NOT reboot. So following your latest advice, by rebooting after every step, I did notice that the alarmdotcom folder did get removed on it's own and I did not need to delete it manually. So there's that for some kind of change, but it still fails on any version 2.8 and higher. 

     It could possibly have something to do with the fact that I am with Telus security, and I am not a pure Alarm.com subscriber. Telus uses the Alarm.com login and service, but maybe this has some lingering issue with the latest versions. Just a guess of course. Other than that one guess, I am also thinking it could be as simple as maybe some kind of simple entry elsewhere that needs to removed or updated (just like the alarmdotcom folder needing removal) and isn't being cleared by the latest update of the Alarmdotcom plugin. Again, just a guess. 

     I hope there are more people out there having the issue, I would like to solve it and keep the Alarmdotcom plugin up to date, it is perfect with HA. Thanks again, if there is anything else please write back, fingers crossed I can make it work, short of reinstalling HA from scratch.

**Comment by elahd** [comment]
@rEd2k Do you by chance have a Skybell? If you do, which model do you have? This may be causing the error. I recently added support for setting a few parameters on the Skybell HD, but it's impossible to account for all of the variations with all ADC providers/devices ahead of time. I'll add better error handling around this in a bit, but it would be helpful to have more information around your setup.

It would be great if you could post a screenshot of your Skybell config page on Alarm.com, as well (with sensitive info blacked out).

**Comment by elahd** [comment]
Also, try updating to v0.2.11 and let me know how it works.
