### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by dmiddlet2005** [pyalarmdotcom/alarmdotcom#143]
Unable to complete the install.  After adding the integration and adding the user/password, I am unable to see any entities or devices.  I am also not able to configure the integration.  I have removed the integration also and tried again with the same issue.

![brave_G9OifZ8dqf](https://user-images.githubusercontent.com/29782187/177412558-e4871423-98a6-4fd3-85a0-135ad7f476fe.png)
![brave_qeB2aiVaRW](https://user-images.githubusercontent.com/29782187/177412560-d6b54a66-ef3e-4c7c-b5e5-6cd3a8dd348c.png)

**Comment by elahd** [comment]
Which version of HA are you using?

**Comment by dmiddlet2005** [comment]
Just updated to 2022.7.2 Core.  Seems to be working now.

**Comment by elahd** [comment]
Great, thanks for confirming.

For context, Home Assistant requires that integrations be updated occasionally to use new APIs for communicating with Home Assistant. I think I did that in the last release. There used to be a way to specify a minimum Home Assistant version for each integration version in HACS, but that feature was pulled back a few months ago. Not sure why.
