### ISSUE TITLE
Multiple Instances of the HA Integration for Separate Properties?

### ISSUE THREAD

**Issue by pldmgg** [pyalarmdotcom/alarmdotcom#145]
Are separate "systems" (as Alarm.com refers to them) at different locations supported? I was just going to add a dedicated user login for the second property and then try to add a second instance of this integration in Home Assistant. Is that the way to do it?

**Comment by elahd** [comment]
Yep, that’s supported. Just add the integration a second time with a second
set of credentials.

**Comment by pldmgg** [comment]
For some reason, the second instance doesn't accept my 2-factor code. 2-Factor works fine if I just login via the website though. I'm not seeing anything in the HA System Logs at all so not sure what the issue might be.

**Comment by elahd** [comment]
Can you try deleting both accounts from Home Assistant, restarting, then adding them both one right after the other?
