### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by zeieri** [pyalarmdotcom/alarmdotcom#150]
Hi There!

First off, great looking integration! I'm super excited to get this off the ground!

I've installed this app via HACS. I've restarted Home Assistant. When I go to Settings > Devices & Services > Add Integration, this integration does not show up!

Here is my HA version info:

<html>
<body>

Version | core-2022.7.5
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.45
CPU Architecture | x86_64

</body>
</html>

<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(225, 225, 225); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(28, 28, 28); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Home Assistant Supervisor</h3></div>

Host Operating System | Home Assistant OS 8.2
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.07.0
Agent Version | 1.2.1
Docker Version | 20.10.14
Disk Total | 30.8 GB
Disk Used | 6.1 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok
Installed Add-ons | File editor (5.3.3), Terminal & SSH (9.6.0), AppDaemon (0.9.1)

</body>
</html>

<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(225, 225, 225); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(28, 28, 28); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Home Assistant Community Store</h3>
GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.26.2
Stage | running

</body>
</html>

I notice the readme shows steps from before the latest and greatest change for HA. Could that be part of the problem?

Thank you!

**Comment by zeieri** [comment]
Oh forgot to add, I did verify I'm running this repository and the latest version (v0.2.11).

Thanks!

**Comment by zeieri** [comment]
Sorted! I deleted the folder for this integration from custom_components, restarted Home Assistant and re-installed from scratch!

**Comment by elahd** [comment]
Awesome!
