### ISSUE TITLE
Unable to reconfigure or reload

### ISSUE THREAD

**Issue by tcm0116** [pyalarmdotcom/alarmdotcom#154]
My integration failed to configure for reasons I'm still looking into. However, when attempting to reconfigure, I get the following:

![Screenshot_20220727-080830](https://user-images.githubusercontent.com/1868773/181243704-985e7049-14ce-47fd-be47-25f3d5f78512.png)

If I try and reload the integration, I get the following error in the log:

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172
First occurred: July 25, 2022 at 11:14:40 PM (11 occurrences)
Last logged: 8:09:08 AM

Error unloading entry Brinks Home™:xyz@gmail.com for light
Error unloading entry Brinks Home™:xyz@gmail.com for button
Error unloading entry Brinks Home™:xyz@gmail.com for number
Error unloading entry Brinks Home™:xyz@gmail.com for switch
Error unloading entry Brinks Home™:xyz@gmail.com for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 118, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by elahd** [comment]
The "Config entry was never loaded!" error message was removed a few versions ago, so it looks like you're on an old version of the integration. Can you update to 0.2.14 and try again?

**Comment by tcm0116** [comment]
It turns out that the newer versions of the component aren't compatible with older versions of Home Assistant. I was using core 2022.3 since that's the last version that supports the legacy z-wave integration and I didn't want to migrate due to all of the issues I had been reading about. I updated the component and discovered these. 

You may want to consider indicating that the newer versions of the component require newer versions of Home Assistant.

**Comment by elahd** [comment]
Got it, sorry about that. There used to be a feature in HACS that allowed integration developers to specify a minimum Home Assistant version, but that doesn't seem to be working anymore. It's also tough as an integration developer to know which integration features are supported by which HA version. I think that this is deliberate -- the HA team runs under the assumption that everyone is using the most up to date version of HA.

For what it's worth, I've been using the Z-Wave JS to MQTT add-on for over a year with no issues. You may just want to back up your instance and bite the bullet with the migration 😬.
