### ISSUE TITLE
Retrying setup error after upgrade to Supervisor 2022.08.3

### ISSUE THREAD

**Issue by rubicon** [pyalarmdotcom/alarmdotcom#163]
I just upgraded to HA Supervisor 2022.08.3. After reboot, I now get this error:

`Retrying setup: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.alarm.com/web/api/video/cameras/')`

I surf to that URL and get a page not found error. 

Restarts seem to have no effect. I've logged into the iOS App and website for alarm.com to see if there were any blocking prompts and there were not. 

Here are the versions I'm running on a Home Assistant Blue:

Home Assistant 2022.8.3
Supervisor 2022.08.3
Operating System 8.4
Frontend 20220802.0 - latest

**Comment by odjhl88** [comment]
I'm having the exact same issue. This does seem to be an issue with the current release of Home assistant.

**Comment by elahd** [comment]
It looks like you're using an older version of the integration. Can you try again with v0.2.14?

**Comment by sceccola** [comment]
I am getting the same error, how do you tell what version you are using.  I deleted the integration and readded.  I am still getting the error.

**Comment by elahd** [comment]
It's not so easy to see that via HACS anymore. Try deleting the integration from HACS and redownloading it. We recently moved the integration into a different GitHub repo, so anyone with an existing install will need to remove/reinstall via HACS to be linked to the new repo.

**Comment by sceccola** [comment]
I did that to know avail.   Any other suggestions.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by odjhl88** [comment]
Okay, not sure why this worked but here's what I did to fix this error.

1.  Delete the existing alarm.com integration
2. re-download the integration from HACS
3. Rebooted HA

Now everything is working again.

**Comment by reyrios** [comment]
Last night an this morning it wasn't working. I just went to drop something off and came back and it is working.  I did nothing.

**Comment by sceccola** [comment]
i just redownloaded and still not working

**Comment by sceccola** [comment]
i restarted and its working

**Comment by rubicon** [comment]
> It looks like you're using an older version of the integration. Can you try again with v0.2.14?

I went to HACS and installed the new repo version (v0.2.15), restarted, and all is good. Thank you, @elahd. 

I would recommend you update the HACS text, as it currently doesn’t say anything and a note about the repo move would have helped. Thanks again for the help and the great work.

**Comment by elahd** [comment]
Great, thanks for the update!  Unfortunately, there's no way to update the text in HACS once you move the integration. Learned that one the hard way.
