### ISSUE TITLE
Armed state doesn't currently refresh on it's own if changed outside of home assistant

### ISSUE THREAD

**Issue by rmatte** [pyalarmdotcom/alarmdotcom#164]
If someone disables our alarm system at the panel it continues to display as Armed on the home assistant dashboard.  The state never gets updated automatically there to reflect the new state.  I need to manually click "disarm" on the dashboard to have it show as Disarmed. It seems like the state used to update on it's own but maybe I'm just misremembering.  It would be great if it would periodically poll (maybe every minute) to check the state and update it accordingly if it changes.  Thanks.

**Comment by Anto79-ops** [comment]
This something I've noticed also here:

https://github.com/pyalarmdotcom/alarmdotcom/issues/160#issuecomment-1211014175

Funny thing is, it didn't do it this morning, but did it 2 morning before.

**Comment by rmatte** [comment]
> This something I've noticed also here:
> 
> [#160 (comment)](https://github.com/pyalarmdotcom/alarmdotcom/issues/160#issuecomment-1211014175)
> 
> Funny thing is, it didn't do it this morning, but did it 2 morning before.

I've had it happen several mornings in a row for me now.  Our kid heads to school around 7am and disables the alarm panel around 6:30am.  I wake up at 8am and then check the dashboard around 8:15 or 8:30 and it's still showing as "Armed" even though I can clearly see that the panel has a green light on it indicating that it has been disarmed.

**Comment by rmatte** [comment]
> This should be fixed in v0.2.15. Can you update and try again?

Once v0.2.15 makes it in to HACS I'll give it a try.  Thanks :)

**Comment by elahd** [comment]
HACS periodically checks GitHub for updates. You can force it to check on demand by clicking on the integration in HACS, then clicking "Update information":

![image](https://user-images.githubusercontent.com/466460/184187537-d0a366e9-1505-4bf2-9633-f4ca3e44ac1a.png)

That should trigger the update integration prompt.

**Comment by Valdorama** [comment]
Updated and the arming status is now correct. Will report back if the status fails to update the next time it's changed.

Thanks for the fix.
