### ISSUE TITLE
Alarm.com integration failing with json error

### ISSUE THREAD

**Issue by ejbrownie** [pyalarmdotcom/alarmdotcom#166]
The alarm.com integration is failing with the following error:

Retrying setup: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.alarm.com/web/api/video/cameras/')

I have deleted and readded the integration but still receive the same error.

**Comment by ssambhi900** [comment]
I am having the same issue. Was it ever resolved??
