### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'async_disarm'

### ISSUE THREAD

**Issue by padlocked17** [pyalarmdotcom/alarmdotcom#167]
Getting this error when attempting to call “alarm_control_panel.disarm_alarm”

Everything works after a HA restart for a little while and then this pops up every time after ~12hrs. 

`File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 144, in async_alarm_disarm
    await self._device.async_disarm()
AttributeError: 'NoneType' object has no attribute 'async_disarm'
`

**Comment by elahd** [comment]
Which version of the integration are you using?

**Comment by padlocked17** [comment]
Pretty sure this was under 0.2.13. I just updated to .15, and I’ll give it a day or two to see if you got this nailed down in one of the subsequent releases.

**Comment by padlocked17** [comment]
Looks corrected with the latest release. Will close this now. Thanks!
