### ISSUE TITLE
Cannot reliably login since 2022.8 upgrade

### ISSUE THREAD

**Issue by bfish2** [pyalarmdotcom/alarmdotcom#168]
Intermittently since 2022.8 upgrade of HASS, but more frequently past week or two, I cannot login to alarm.com via HASS and get the following error on Integrations page:

Retrying setup: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.alarm.com/web/api/video/camera

I have tried deleting and re-adding Integration but to no availl

**Comment by ssambhi900** [comment]
I am having the same issue. Tried uninstalling and re-installing.

**Comment by elahd** [comment]
We recently moved the integration to a new GitHub repo not realizing that this would cut off existing users from upgrades. 

The issue you're reporting is resolved, but you'll need to do some work to update:

- Delete the integration from Home Assistant via the Integrations page.
- Delete the integration from HACS. 
- Re-download the integration via HACS. 
- Restart Home Assistant. 
- Re-add the integration from the integrations page. 

Sorry for the trouble. Please let me know how this works for you.

**Comment by ssambhi900** [comment]
> We recently moved the integration to a new GitHub repo not realizing that this would cut off existing users from upgrades.
> 
> The issue you're reporting is resolved, but you'll need to do some work to connect your HA server to the new repo:
> 
> 1. Delete the integration from Home Assistant via the Integrations page.
> 2. Delete the integration from HACS.
> 3. Re-download the integration via HACS.
> 4. Restart Home Assistant.
> 5. Re-add the integration from the integrations page.
> 
> Sorry for the trouble. Please let me know how this works for you.

Thank you!  All good now!

**Comment by bfish2** [comment]
This seems to have solved it.  THANK YOU!
