### ISSUE TITLE
unable to arm from app or web browser

### ISSUE THREAD

**Issue by pdobrien3** [pyalarmdotcom/alarmdotcom#172]
Your Alarm.com user does not have permission to arm_away the alarm control panel, None. Please log in to Alarm.com to grant the appropriate permissions to your account.

have not noticed issues with automations arming though.  seems weird.

my user has full control on ADC

**Comment by Valdorama** [comment]
Got this same error this morning too, but I also can't disarm from the Alarm.com app either, so maybe it's a problem at their end.

**Comment by pdobrien3** [comment]
Yes, seems to be working now.
