### ISSUE TITLE
Adding more systems

### ISSUE THREAD

**Issue by PerfectBake420** [pyalarmdotcom/alarmdotcom#174]
I am hoping there is a way to add more than 1 system to HA. I have the integration working with my main facility. The Maintenance building has its own security system. I would like to add this in as well. In alarm.com, I can see both from 1 login and I have a seperate login for it as well. 
With my main facility loaded, it does not show the connected systems only the main system. When I load a second instance of the Alarm.com integration, it shows 2 accounts integrated, however, it overwrites the sensor data I had with the original integration. They both show the same sensors. 
Is there a way to do what I am wanting?

**Comment by timpeq** [comment]
I think the way you might do this now is to edit all of the entities it to have unique names before adding additional accounts.  This is just a workaround obviously, it sounds like we need an option to add prefix to all entity ids, unique to each account.

**Comment by elahd** [comment]
@PerfectBake420 If you're able to get me some more information I can take a stab at fixing this. To help, please do the following:

1. Install the pyalarmdotcomajax `adc` command line tool using [these instructions](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#install-the-adc-command-line-tool).
2. Run the "Raw JSON" command from the instructions page.
3. Paste here whatever shows up in the "PARTITION" and "SYSTEM" sections.

Thanks!

**Comment by elahd** [comment]
Closing as stale.

**Comment by Taralas** [comment]
Any interest in picking this back up? I am in a similar situation, and would be able to provide the requested information.
