### ISSUE TITLE
Arm Home - No countdown when opening door

### ISSUE THREAD

**Issue by millerjryan** [pyalarmdotcom/alarmdotcom#175]
Not sure if this is an issue with my alarm configuration or the integration.  When I arm home through the integration and open any door the alarm immediately triggers. 

When I ARM home from the Alarm.com app, this isn't the case and I am met with a countdown to disarm.   Is there a setting I am missing?

**Comment by elahd** [comment]
In HA, go to Settings > Integrations. Click on the "Configure" button for the ADC integration. Hit next. You'll see these options:

![image](https://user-images.githubusercontent.com/466460/208159036-e3d5bbaf-a5b4-4219-8ee5-20e213e35a75.png)

Check "Arming Delay" for "Arm Home", then submit. That should fix it.
