### ISSUE TITLE
Help with alarm_trigger Service

### ISSUE THREAD

**Issue by mjrainwater** [pyalarmdotcom/alarmdotcom#177]
I am able to see an "alarm_trigger" service.  However, I receive an error when I attempt to call the service in Node-Red.

Has this service been written, or is it a shell in beta, etc?

This would be a useful service to allow me to trigger an alarm from Home Assistant using sensors that are not directly supported by my Alarm.com provider (FrontPoint).  I would like to be able to trigger an alarm from rules I created in Node Red.

Thank you.

**Comment by elahd** [comment]
This hasn't been implemented. It looks like the ADC in-app panic feature is only available via their mobile apps, not via the web site. This integration can only use the services available via the ADC website.
