### ISSUE TITLE
Disarm and Arm Without Entering Code

### ISSUE THREAD

**Issue by rbiffle** [pyalarmdotcom/alarmdotcom#184]
Morning,
Is there a way to arm and disarm the panel without having to enter in the arm/disarm code?  I currently use Homebridge and their Alarm.com plugin because it allows me to arm and disarm my alarm without the need to enter the arm/disarm code each time via HomeKit.  That is the only reason i have Homebridge.

If I could figure out how to get Homeassistant and your Alarm.com plugin to allow arming and disarming without the code, I coudl blow away HomeBridge.  I realize the safety issues I am trying to get around.

Thanks!

**Comment by elahd** [comment]
Try this.

1. Set a PIN for your Alarm.com alarm control panel in Home Assistant. (I realize that this is the opposite of what you want to do, but bear with me.)
2. Manually configure the HomeKit integration via configuration.yaml using [these instructions](https://www.home-assistant.io/integrations/homekit/#manual-configuration).
3. Configure the alarm_control_panel in HomeKit using the same PIN that you set in the Alarm.com integration:

```yaml
    entity_config:
      alarm_control_panel.your_control_panel_name:
        code: 1234
```

I _think_ that this will cause the HomeKit integration to automatically pass the PIN to the Alarm.com integration without prompting you.

Let me know if this works!

**Comment by elahd** [comment]
@rbiffle Any luck?
