### ISSUE TITLE
Two-Factor Authentication Required?

### ISSUE THREAD

**Issue by cmaglio** [pyalarmdotcom/alarmdotcom#185]
Upon trying to setup the integration, after entering in my credentials, I am receiving the error message below...

![image](https://user-images.githubusercontent.com/37604281/206303764-d2f931b4-a436-4402-acaf-ac566cfed679.png)

I figured two-factor was required, so I setup 2FA on my ADC account (via text message). However, I am still receiving the same error message.

Is there a specific type of 2FA that is required, or why would I be seeing this message if 2FA is enabled?

I have not found any pertinent information in the setup guide of this integration nor searching around of why I would be receiving this error. 🤷‍♂️ Hopefully, I've just missed something.

**Comment by ncundari** [comment]
Having the same issue.

**Comment by elahd** [comment]
Looks like there's an issue with new installs. I'll take a look soon.

**Comment by cmaglio** [comment]
Well, I was hoping I just did something wrong as to not cause extra work. Appreciate you looking into this though!

**Comment by elahd** [comment]
This is fixed in v2.0.17. Can you confirm that this works on your end?

**Comment by ncundari** [comment]
Works on my end! Thank you!

**Comment by cmaglio** [comment]
Also works for me, thanks for the fix! 

As a side note, do you know what ADC considers abuse as far as the update rate? I am seeing that you can miss when a door is opened if it is opened and then closed between update intervals. 

It's totally understandable why this is considering the limitations from ADC and the lack of a real API... I'm just curious what we can reduce this to without being locked out. Thanks again!

**Comment by elahd** [comment]
You can definitely miss events. I've seen people post here with some ridiculously low update times, but I'm not sure of how that worked out for them long term. Try using a low refresh setting on a dedicated Alarm.com account for Home Assistant. Worst case is that account will be temporarily banned. (At your own risk, but I doubt they'll kick you off the service for a one-time offense. I've done far worse during development/debugging.)

The long term solution is to write new code that pulls sensor history on each refresh and triggers missed events late or finding a way to tie into ADC's webhook / notification system for real time push alerts. The latter is the best approach but likely requires a full rewrite of the integration.

**Comment by cmaglio** [comment]
Great info, and thanks again for the quick fix!
