### ISSUE TITLE
Random phantom light error

### ISSUE THREAD

**Issue by Aipoc76** [pyalarmdotcom/alarmdotcom#188]
I keep receiving this error every few hours give or take a hour.  I've looked through my devices, and i do not have a sensor named None.  No buttons i created trigger this error, im at a loss. Any suggestions would be greatly appreciated.

```
Alarm.com Error
Your Alarm.com user does not have permission to turn on the light, None. Please log in to Alarm.com to grant the appropriate permissions to your account.
```

**Comment by elahd** [comment]
Upgrade to v0.2.18. I added more details to the error prompt and fixed a bug. You should now see the entity name and entity ID in the error. That should help track down the issue. Please report back with an update!

**Comment by Aipoc76** [comment]
Thanks, Have not seen the issue in a few days now.  Im suspecting it may have been a entity that i removed from the alarm panel and replaced, and never refreshed the integration.  But if i do see the error again, ill post here.
