### ISSUE TITLE
Garage door no longer supports closing

### ISSUE THREAD

**Issue by impreza2k3** [pyalarmdotcom/alarmdotcom#196]
My  z-wave garage door openers no longer support the option to close.  This feature worked previously.

They have the following attributes available

Controls:
Open

Diagnostic:
Battery
Debug
Malfunction

Latest version of alarmdotcom integration v2.0.19
Home Assistant 2022.12.9

**Comment by fowlerjk** [comment]
I had the same thing happen, roughly the same time you saw it. [https://github.com/pyalarmdotcom/alarmdotcom/issues/197](url)

**Comment by elahd** [comment]
Thanks. I think I fixed the issue. Can you install the development version of the integration to confirm? See https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug.

**Comment by elahd** [comment]
I think I fixed the issue. Can you install the development version of the integration to confirm? See https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug.

**Comment by impreza2k3** [comment]
> I think I fixed the issue. Can you install the development version of the integration to confirm? See https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug.

I can confirm that it now has the close control and works as expected.  The garage door can be opened and closed.

**Comment by elahd** [comment]
Thanks for confirming -- I pushed out the fix in v2.0.20.
