### ISSUE TITLE
Sensors not updating, "sensor_status" not anywhere

### ISSUE THREAD

**Issue by fowlerjk** [pyalarmdotcom/alarmdotcom#197]
I use CPI, which runs through Alarm.com, and most everything is good except for two things:

- No doors are ever sensed "open"
- No option to close garage door, which I'm sure is related to it always being considered closed

I did some digging and found that I should be looking at "sensor_state" in the panel attributes...but there's no such thing. This is all I have:
`supported_features: 7
code_arm_required: true
mac_address: ''
desired_state: Disarmed
uncleared_issues: false
friendly_name: Panel`

**Comment by elahd** [comment]
Hey. See #196 for updates on the garage door issue. As for doors not being sensed open -- I can't replicate the issue on my end. Can you [provide debug data](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#get-debug-data-for-a-single-entity) for one of your doors in both the open and closed states? Thanks!
