### ISSUE TITLE
async_setup_platforms error in beta 2023.2.0b0

### ISSUE THREAD

**Issue by pdobrien3** [pyalarmdotcom/alarmdotcom#203]
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for alarmdotcom using this method at custom_components/alarmdotcom/__init__.py, line 124: hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)

**Comment by elahd** [comment]
Thanks for reporting this. It's fixed and will be included in the next release!
