### ISSUE TITLE
Warning method going away

### ISSUE THREAD

**Issue by ZombieBunnyOrg** [pyalarmdotcom/alarmdotcom#209]
If you have not seen it already, just letting you know that this will need to be updated or will stop working on the next version of HA

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for alarmdotcom using this method at custom_components/alarmdotcom/__init__.py, line 124: hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)

**Comment by lucdetellis** [comment]
Yes, I am getting the same warning:

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: February 11, 2023 at 11:57:32 PM (1 occurrences)
Last logged: February 11, 2023 at 11:57:32 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups;
this will fail in version 2023.3. Please report issue to the custom integration author for alarmdotcom
using this method at custom_components/alarmdotcom/__init__.py, line 124:
hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
```

Looks like I will be avoiding the March software update until this is fixed.

**Comment by lucdetellis** [comment]
@elahd Thanks so much for the quick fix!
