### ISSUE TITLE
Cannot determine binary sensor state. Found raw state of DeviceState.DRY.

### ISSUE THREAD

**Issue by Raul-7-7** [pyalarmdotcom/alarmdotcom#211]
Seeing this error in logs after the latest update

Logger: custom_components.alarmdotcom.binary_sensor
Source: custom_components/alarmdotcom/binary_sensor.py:106
Integration: Alarm.com ([documentation](https://github.com/pyalarmdotcom/alarmdotcom), [issues](https://github.com/pyalarmdotcom/alarmdotcom/issues))
Cannot determine binary sensor state. Found raw state of DeviceState.DRY.

**Comment by elahd** [comment]
@Raul-7-7 Can you see if this works with v2.1.1-alpha?

**Comment by Raul-7-7** [comment]
@elahd that did the trick! working fine in 2.1.1-alpha. 
Thank you for the quick fix!

**Comment by elahd** [comment]
Awesome, thanks! I'll release as non-alpha shortly.
