### ISSUE TITLE
ADC-VDB780B

### ISSUE THREAD

**Issue by karthikmannem1991** [pyalarmdotcom/alarmdotcom#216]
ADC-VDB780B
https://doorbell.poweredbyalarm.com/vdb780b-install/

**Where does this device appear in the Alarm.com mobile app?**
Doorbell Camera

**Comment by elahd** [comment]
Can you provide endpoint / JSON information for this device? Requirements are listed in the [template for a new device request](https://github.com/pyalarmdotcom/alarmdotcom/issues/new?assignees=&labels=new+device&template=requesting-support-for-new-devices.md&title=%5BNEW+DEVICE%5D+).

**Comment by karthikmannem1991** [comment]
{
            "id": "102347524-2051",
            "type": "video/devices/camera",
            "attributes": {
                "supportsSnapShot": true,
                "canTakeSnapshot": true,
                "supportsRecording": true,
                "canRequestRecording": true,
                "canUploadClips": true,
                "maxSvrClipDownloadDurationSec": 3600,
                "username": "123",
                "hasSvrSchedule": false,
                "onvifParentId": null,
                "excludedFromVisualVerification": false,
                "excludedFromEscalatedEvents": false,
                "liveViewHdToggleEnabled": true,
                "supportsEndToEndWebRTCStreaming": false,
                "supports4MPStreaming": false,
                "supportsSiren": false,
                "canSirenBeActivatedByLogin": false,
                "isSirenEnabledInSettings": false,
                "isSirenPlaying": false,
                "osdOverlayEnabled": false,
                "canPanTilt": false,
                "maxPanTiltLevel": 0,
                "canZoom": false,
                "maxZoomLevel": 0,
                "minZoomLevelForPanTilt": 0,
                "panTiltPresets": [],
                "preferredPanTiltPreset": null,
                "isUnreachable": false,
                "lastSuccessfulSupervision": "2023-02-12T02:20:36.293Z",
                "canStreamToPanel": true,
                "canChangeStreamToPanel": true,
                "canStreamToPanelBeEnabled": true,
                "isStreamToPanelEnabled": true,
                "doorbellChimeType": 1,
                "supportedDoorbellWedgeOptions": null,
                "doorbellWedgeType": 0,
                "supportsWedgeYesNo": false,
                "supportsWedgeGIF": false,
                "supportsVmdSchedules": false,
                "deviceImagePath": "/web/webimages/camera_images/VDB780B_64px.png?v=2",
                "deviceModel": "ADC-VDB780B",
                "macAddress": "xxxxxxxxxxx",
                "firmwareVersion": "2.4.1.081",
                "publicIp": "xxxxxxxxx",
                "privateIp": "xxxxxxxxx",
                "port": "80",
                "httpsPort": "443",
                "shouldUseEntireImageForSnapshot": false,
                "hasDdnsed": false,
                "usageProtocolMapping": {
                    "18": 1,
                    "9": 1,
                    "10": 1,
                    "6": 1,
                    "20": 1
                },
                "isVirtualCamera": false,
                "isVarifocalCamera": false,
                "hasSdRecordingSchedule": false,
                "isBatteryCameraAndUsingGatewayForBackendAccess": true,
                "supportsLiveView": true,
                "forcedAspectRatio": null,
                "canBeSaved": false,
                "canChangeDescription": false,
                "description": "Doorbell",
                "deviceModelId": 0,
                "canConfirmStateChange": false,
                "canReceiveCommands": false,
                "remoteCommandsEnabled": false,
                "hasPermissionToChangeState": false,
                "deviceIcon": {
                    "icon": 27
                },
                "batteryLevelNull": null,
                "lowBattery": false,
                "criticalBattery": false
            },
            "relationships": {
                "videoEvents": {
                    "data": [],
                    "meta": {
                        "count": "0"
                    }
                },
                "password": {
                    "data": {
                        "id": "102347524-2051",
                        "type": "video/cameraPassword"
                    }
                },
                "videoSource": {
                    "data": {
                        "id": "102347524-2051",
                        "type": "video/videoSources/liveVideoSource"
                    }
                },
                "videoSourceHd": {
                    "data": {
                        "id": "102347524-2051",
                        "type": "video/videoSources/liveVideoHighestResSource"
                    }
                },
                "svrVideoSource": {
                    "data": {
                        "id": "102347524-2051",
                        "type": "video/videoSources/svrVideoSource"
                    }
                },
                "svrScrubberThumbnailEndpoint": {
                    "data": {
                        "id": "102347524-2051",
                        "type": "video/svrThumbnailEndpoint"
                    }
                },
                "cameraSiren": {
                    "data": null
                },
                "liveVideoSetting": {
                    "data": {
                        "id": "102347524-2051",
                        "type": "video/live-video-setting"
                    }
                },
                "snapshot": {
                    "data": {
                        "id": "102347524-2051",
                        "type": "video/snapshot"
                    }
                },
                "privacyZonesSetting": {
                    "data": null
                },
                "system": {
                    "data": {
                        "id": "12385880",
                        "type": "systems/system"
                    }
                },
                "stateInfo": {
                    "data": null
                }
            }
        },

**Comment by elahd** [comment]
Are you able to reverse engineer the streaming mechanism that Alarm.com uses? I don't have access to an ADC camera so I can't do this myself.

**Comment by elahd** [comment]
Closing to merge with #101. Let's move this conversation there.
