### ISSUE TITLE
ADC-V723x

### ISSUE THREAD

**Issue by karthikmannem1991** [pyalarmdotcom/alarmdotcom#217]
ADC-V723x
https://www.alarmsystemstore.com/products/alarm-com-adc-v723-outdoor-1080p-wi-fi-camera

**Comment by elahd** [comment]
Can you provide endpoint / JSON information for this device? Requirements are listed in the [template for a new device request](https://github.com/pyalarmdotcom/alarmdotcom/issues/new?assignees=&labels=new+device&template=requesting-support-for-new-devices.md&title=%5BNEW+DEVICE%5D+).

**Comment by karthikmannem1991** [comment]
====[ Camera ]====

{
    "data": [
        {
            "id": "102347524-2049",
            "type": "video/devices/camera",
            "attributes": {
                "supportsSnapShot": true,
                "canTakeSnapshot": true,
                "supportsRecording": true,
                "canRequestRecording": true,
                "canUploadClips": true,
                "maxSvrClipDownloadDurationSec": 3600,
                "username": "123",
                "hasSvrSchedule": false,
                "onvifParentId": null,
                "excludedFromVisualVerification": false,
                "excludedFromEscalatedEvents": false,
                "liveViewHdToggleEnabled": true,
                "supportsEndToEndWebRTCStreaming": true,
                "supports4MPStreaming": false,
                "supportsSiren": false,
                "canSirenBeActivatedByLogin": false,
                "isSirenEnabledInSettings": false,
                "isSirenPlaying": false,
                "osdOverlayEnabled": false,
                "canPanTilt": false,
                "maxPanTiltLevel": 0,
                "canZoom": false,
                "maxZoomLevel": 0,
                "minZoomLevelForPanTilt": 0,
                "panTiltPresets": [],
                "preferredPanTiltPreset": null,
                "isUnreachable": false,
                "lastSuccessfulSupervision": "2023-02-24T13:13:46.957Z",
                "canStreamToPanel": true,
                "canChangeStreamToPanel": true,
                "canStreamToPanelBeEnabled": true,
                "isStreamToPanelEnabled": true,
                "doorbellChimeType": -1,
                "supportedDoorbellWedgeOptions": null,
                "doorbellWedgeType": 0,
                "supportsWedgeYesNo": false,
                "supportsWedgeGIF": false,
                "supportsVmdSchedules": true,
                "deviceImagePath": "/web/webimages/camera_images/V723_64px.png?v=2",
                "deviceModel": "ADC-V723X",
                "macAddress": "xxxxxxxxxx",
                "firmwareVersion": "0.6.6.770",
                "publicIp": "xxxxxxxxxx",
                "privateIp": "xxxxxxxx",
                "port": "40926",
                "httpsPort": "41926",
                "shouldUseEntireImageForSnapshot": false,
                "hasDdnsed": true,
                "usageProtocolMapping": {
                    "18": 1,
                    "9": 1,
                    "10": 1,
                    "6": 1,
                    "20": 1
                },
                "isVirtualCamera": false,
                "isVarifocalCamera": false,
                "hasSdRecordingSchedule": false,
                "isBatteryCameraAndUsingGatewayForBackendAccess": false,
                "supportsLiveView": true,
                "forcedAspectRatio": 1.77777779,
                "canBeSaved": false,
                "canChangeDescription": false,
                "description": "myCamera",
                "deviceModelId": 0,
                "canConfirmStateChange": false,
                "canReceiveCommands": false,
                "remoteCommandsEnabled": false,
                "hasPermissionToChangeState": false,
                "deviceIcon": {
                    "icon": 27
                },
                "batteryLevelNull": null,
                "lowBattery": false,
                "criticalBattery": false
            },
            "relationships": {
                "videoEvents": {
                    "data": [],
                    "meta": {
                        "count": "0"
                    }
                },
                "password": {
                    "data": {
                        "id": "102347524-2049",
                        "type": "video/cameraPassword"
                    }
                },
                "videoSource": {
                    "data": {
                        "id": "102347524-2049",
                        "type": "video/videoSources/liveVideoSource"
                    }
                },
                "videoSourceHd": {
                    "data": {
                        "id": "102347524-2049",
                        "type": "video/videoSources/liveVideoHighestResSource"
                    }
                },
                "svrVideoSource": {
                    "data": {
                        "id": "102347524-2049",
                        "type": "video/videoSources/svrVideoSource"
                    }
                },
                "svrScrubberThumbnailEndpoint": {
                    "data": {
                        "id": "102347524-2049",
                        "type": "video/svrThumbnailEndpoint"
                    }
                },
                "cameraSiren": {
                    "data": null
                },
                "liveVideoSetting": {
                    "data": {
                        "id": "102347524-2049",
                        "type": "video/live-video-setting"
                    }
                },
                "snapshot": {
                    "data": {
                        "id": "102347524-2049",
                        "type": "video/snapshot"
                    }
                },
                "privacyZonesSetting": {
                    "data": {
                        "id": "102347524-2049",
                        "type": "video/privacy-zones-setting"
                    }
                },
                "system": {
                    "data": {
                        "id": "12385880",
                        "type": "systems/system"
                    }
                },
                "stateInfo": {
                    "data": null
                }
            }
        }
    ],
    "included": [],
    "meta": {
        "transformer_version": "1.1"
    }
}

**Comment by elahd** [comment]
Closing to merge with #101.
