### ISSUE TITLE
Add Poll Alarm Status Command

### ISSUE THREAD

**Issue by movieguy2001** [pyalarmdotcom/alarmdotcom#218]
Short version:  I would like to be able to poll the alarm for state only when certain conditions are met in HA during an automation rather than using a polling interval.  Would it be possible to add a command for this in the integration?

Longer version:  I use zwave relays to immediately expose alarm state to HA (using zwave contact sensors wired to the relays).  I have an automation set up right now to arm/disarm alarm based on the state of these contacts.  This allows me to take immediate action when the alarm system state changes rather than waiting till a poll interval is triggered in the integration.   The only issue I have is that when I send a disarm command through HA after the alarm system has been disarmed at the panel - HA will send a duplicate disarm command to the system and I get a warning message the panel saying it cant disarm the system because it isnt in a state where this is possible.  It would be nice if I could just turn off polling completely and only trigger a poll of the system when I detect a change in the contact's status.  

Thank you.

**Comment by elahd** [comment]
I’m planning on building web socket support soon. That is, the integration
would get real time push notifications from ADC. It would still poll to
make sure things stay synced, but much less frequently. Would that work for
you?

Can you explain in more detail the issue with disarming? Is the problem
that when you disarm directly at the panel, the disarmed status isn’t being
reflected in HA soon enough?

**Comment by movieguy2001** [comment]
Websocket support would probably replace my whole need for the relays so it would be very welcome.

I have the Control Panel setup to close a replay when armed to away or a second relay when armed to home.  These relays are soldered to contacts that are joined to my HA system so they can immediately check when the system is armed to hone/away and take immediate action.  I used this to immediately shut off lights when armed to home, for example.  I also have it set up to send a duplicate comment to the HA integration so its state matching the actual alarm system in real time.  The only issue I am having with the integration is that when I disarm the alarm directly from the panel (the most likely use case in my house) the HA system detects this through the contacts and sends a disarm command AFTER the system has already been disarmed.  This causes an error to briefly display on the screen of the panel that the system cannot be disarmed from its current state (because it's already disarmed).  

Using my current setup, I would like to just send a sync/poll command to the integration rather than an arm/disarm whenever the contacts states change.   However the webhook solution would work great as well and would also solve the problem and would almost remove the needs for my relays/contacts.

**Comment by elahd** [comment]
This is released in v3.0.1.
