### ISSUE TITLE
Arming status badges aren’t showing red and orange colors anymore only green and blue

### ISSUE THREAD

**Issue by k3tfm** [pyalarmdotcom/alarmdotcom#223]
Home Assistant 2023.2.5 Frontend 20230202.0 - latest
HACS Integration version:	1.30.1
AlarmDotCom v2.20
Running as a docker instance in Ubuntu 22.04.2 LTS

After an upgrade somewhere along the line (sorry I know that part isn’t helpful) the AlarmDotCom integration changed how the badge colors indicate the status of the system, meaning:

In HAS it used to be that: 
Red=Away 
Orange=Stay and 
Green=Disarmed

Now the badge in HAS shows:
Green = Armed Stay as well as Armed Away
Blue with a line through it = Dis-Armed

Is this the intended result?

If so, is there a way to configure it to the way it used to be indicating via color of the status, meaning Red=Away, Orange=Stay and Green=Disarmed?

Thank you in advance,
—bh

**Comment by elahd** [comment]
This is likely due to an upstream change in the Home Assistant frontend and, potentially, with a theme that you have installed. I can't replicate the issue on my end and don't believe that integrations are able to set theme colors in this way. home-assistant/frontend#14831 made alarm control panel states themeable. It's possible that your existing HA frontend theme is now able to apply colors in ways that it had not before.

**Comment by k3tfm** [comment]
Howdy and thank you for the response.

I don't have any themes loaded.

Just so I am sure, on your end you see your Alarm.com state badges as Red, Orange(Armed), and Green(DisArmed) and not what I am seeing meaning Green(Armed) and Blue(Disarmed)? I just want to make sure of this before I chase this down any further.

Meaning, I want to make sure what I am experiencing is abnormal.

Thank you in advance,
-bh

**Comment by elahd** [comment]
I see green for armed and gray for disarmed, which appears to be the new Home Assistant standard. See the discussion at home-assistant/frontend#14802.

**Comment by k3tfm** [comment]
Thank you sooooo much! That got me on the right track!

For alarm systems, Green (for the most part) is the desired color for 'Disarmed' (Meaning safe to enter). Having green as armed is counter intuitive for most users.

Anyway ....

Activating themes and adding the below into my themes.yaml returned functionality to the desired result.

Thanks again!!

themes.yaml below for has ver 2023.2.5
---------------------<SNIP>------------------------
Classic:
state-alarm_control_panel-armed_home-color: '#F44336' # Red
state-alarm_control_panel-armed_away-color: '#F44336' # Red
state-alarm_control_panel-arming-color: '#FF9800' # Orange
state-alarm_control_panel-disarmed-color: '#4CAF50' # Green
state-alarm_control_panel-pending-color: '#FF9800' # Orange
state-alarm_control_panel-triggered-color: '#F44336' # Red
state-alert-color: '#F44336' # Red
---------------------</SNIP>------------------------
