### ISSUE TITLE
On Login: Unknown Error Occured

### ISSUE THREAD

**Issue by lrosenman** [pyalarmdotcom/alarmdotcom#224]
When I try to log in to my alarm.com account with the latest (2.2.0) version, I get unknown error occurred.
My account *IS* 2FA/TOTP enabled.
this is with running the code inside the HomeAssistant Container. 

What else can I supply?  How can I help?

**Comment by lrosenman** [comment]
might be related to #220

**Comment by lrosenman** [comment]
If I turn off 2FA it works -- let me know how I can help test.

**Comment by elahd** [comment]
Thanks for reporting this. It's fixed in v2.2.1.
