### ISSUE TITLE
How to install please help 

### ISSUE THREAD

**Issue by Fannar1984** [pyalarmdotcom/alarmdotcom#225]
Hello new to home assistant i hvae try install HACS and I just send me to the addons in home assistant not in addons in HACS is it any other way to install it ?? Need it so much bichuse I have alarm.com 
Regards 
Fannar

**Comment by elahd** [comment]
If you're running into an issue with HACS, take a look at the install instructions at https://hacs.xyz/docs/setup/download, or ask on the HACS discord channel at https://discord.com/invite/apgchf8.
