### ISSUE TITLE
Alarm status not updated

### ISSUE THREAD

**Issue by jwfox5150** [pyalarmdotcom/alarmdotcom#229]
Ever since v2.2.1 there seems to be an issue where if the alarm is armed/disarmed by the physical panel, the status is not updated in the integration until the integration is reloaded. I would be happy to provide additional details, just don't know exactly what you'd want to take a look at.

**Comment by elahd** [comment]
This is probably related to #187. Would you mind [enabling debugging](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging) and checking your full Home Assistant logs for any login, 403, or other obvious errors?

**Comment by jwfox5150** [comment]
Thanks, I will do that. I enabled debugging and it's working just fine on a fresh restart of HA of course - I will wait until this evening and try to replicate. Will post an update when able.

**Comment by jwfox5150** [comment]
Couldn't get it to replicate last night now that debug logging was on, of course! Now that v2.2.2 is released I'm marking this as closed. Thank you so much for your hard work developing this excellent integration!

**Comment by robin-vandaele** [comment]
I have just experienced this issue on 2.2.2. Fine after reload of components. Please reopen. It will enable logs.

**Comment by jwfox5150** [comment]
I just experienced it again on 2.2.2, reopening issue. Of course I had logging disabled - I am going to re-enable debug logging and wait for it to fail again.

**Comment by Raul-7-7** [comment]
I am experiencing the same 
```
Error fetching data from Alarm.com. Got 403 status when fetching data for device type DeviceType.SYSTEM. User is already logged in. Giving up on device type.
Error fetching data from Alarm.com. Got 403 status when fetching data for device type DeviceType.PARTITION. User is already logged in. Giving up on device type.
Error fetching data from Alarm.com. Got 403 status when fetching data for device type DeviceType.SENSOR. User is already logged in. Giving up on device type.
Error fetching data from Alarm.com. Got 403 status when fetching data for device type DeviceType.WATER_SENSOR. User is already logged in. Giving up on device type.
```

**Comment by elahd** [comment]
Folding into #234
