### ISSUE TITLE
Carbon Monoxide always says detected

### ISSUE THREAD

**Issue by surf404** [pyalarmdotcom/alarmdotcom#241]
Hi,

I just installed this integration, everything is fine except my carbon monoxide sensor always shows detected. On alarm.com's website under devices it is showing as OK, any ideas?

Thanks
![2023-03-28 (1)](https://user-images.githubusercontent.com/31177849/228178545-5a0183f7-81fe-49de-9dfd-e062de446cdb.png)
![2023-03-28](https://user-images.githubusercontent.com/31177849/228178582-ff380fe4-b640-4d35-8bea-b260be96aebe.png)

**Comment by surf404** [comment]
> Can you pull debug data for this device using the instructions at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#get-debug-data-for-a-single-entity?

This error originated from a custom integration.

Logger: custom_components.alarmdotcom
Source: custom_components/alarmdotcom/__init__.py:133
Integration: Alarm.com (documentation, issues)
First occurred: 1:59:31 AM (1 occurrences)
Last logged: 1:59:31 AM

ALARM.COM DEBUG DATA FOR Z24 BASEMENT CO: {"deviceType": 6, "openClosedStatus": 3, "state": 2, "isFlexIO": false, "deviceRole": 0, "displayStateText": "Open", "isMonitoringEnabled": false, "sensorNamingFormat": 4, "supportsBypass": false, "supportsImmediateBypass": false, "isBypassed": false, "managedDeviceType": 3, "hasState": false, "canBeRenamed": true, "canBeDeleted": false, "canAccessWebSettings": true, "canAccessAppSettings": false, "webSettings": 400, "canAccessTroubleshootingWizard": false, "troubleshootingWizard": null, "addDeviceResource": 0, "canBeAssociatedToVideoDevice": false, "associatedCameraDeviceIds": {}, "macAddress": "", "manufacturer": "", "isAssignedToCareReceiver": false, "isOAuth": false, "isZWave": false, "supportsCommandClassBasic": false, "isMalfunctioning": false, "canBeSaved": true, "canChangeDescription": true, "description": "Z24 Basement CO", "deviceModelId": 115, "canConfirmStateChange": true, "canReceiveCommands": false, "remoteCommandsEnabled": true, "hasPermissionToChangeState": true, "deviceIcon": {"icon": 218}, "batteryLevelNull": null, "lowBattery": false, "criticalBattery": false}

Thanks

**Comment by elahd** [comment]
Thanks. Can you try again with v3.0.1?

**Comment by surf404** [comment]
> Thanks. Can you try again with v3.0.1?

Installed v3.0.1, still having the same issue

this is the new debug:
This error originated from a custom integration.

Logger: custom_components.alarmdotcom
Source: custom_components/alarmdotcom/__init__.py:158
Integration: Alarm.com (documentation, issues)
First occurred: 2:41:33 PM (1 occurrences)
Last logged: 2:41:33 PM

ALARM.COM DEBUG DATA FOR Z24 BASEMENT CO: {"deviceType": 6, "openClosedStatus": 3, "state": 2, "isFlexIO": false, "deviceRole": 0, "displayStateText": "Open", "isMonitoringEnabled": false, "sensorNamingFormat": 4, "supportsBypass": false, "supportsImmediateBypass": false, "isBypassed": false, "managedDeviceType": 3, "hasState": false, "canBeRenamed": true, "canBeDeleted": false, "canAccessWebSettings": true, "canAccessAppSettings": false, "webSettings": 400, "canAccessTroubleshootingWizard": false, "troubleshootingWizard": null, "addDeviceResource": 0, "canBeAssociatedToVideoDevice": false, "associatedCameraDeviceIds": {}, "macAddress": "", "manufacturer": "", "isAssignedToCareReceiver": false, "isOAuth": false, "isZWave": false, "supportsCommandClassBasic": false, "isMalfunctioning": false, "canBeSaved": true, "canChangeDescription": true, "description": "Z24 Basement CO", "deviceModelId": 115, "canConfirmStateChange": true, "canReceiveCommands": false, "remoteCommandsEnabled": true, "hasPermissionToChangeState": true, "deviceIcon": {"icon": 218}, "batteryLevelNull": null, "lowBattery": false, "criticalBattery": false}

thanks for helping

**Comment by elahd** [comment]
Thanks. It looks like Alarm.com uses states in a weird way with certain sensors (CO, smoke, glass break, among others). I'll need to do some more digging.

**Comment by farberm** [comment]
I am still having the problem that all sensors are unavailable even though website says they are normal, I checked and only have one partition. System is NX-8E.

**Comment by elahd** [comment]
I'm going to remove CO and smoke detectors from the integration. I took a deeper look into [Alarm.com's knowledge base](https://answers.alarm.com/Customer/Website_and_App/User_Management/Web_App_Users/Do_the_app_and_website_update_in_real_time#To_refresh_the_Customer_Website:) and their website's source code and found that smoke and CO detectors don't actually implement state in the same way as motion and contact sensors; they only issue push event notifications when triggered. This integration doesn't yet support event notifications. Including these sensors in the integration is misleading, as these sensors currently only report battery and malfunction states.

I'll re-add these sensors once I can dedicate a couple of hours to triggering sensors while my system is in test mode.

Sorry about this!

**Comment by farberm** [comment]
Still cannot figure out why the malfunction and battery components are working but not the sensor. Says unavailable The website has them available. I have deleted the folder twice. I checked and only have one partition.
<img width="1534" alt="Screenshot 2023-06-02 at 11 24 00 AM" src="https://github.com/pyalarmdotcom/alarmdotcom/assets/16128857/7dd910ee-8d4c-4a72-b389-43a71a6d179e">
<img width="1517" alt="Screenshot 2023-06-02 at 11 27 47 AM" src="https://github.com/pyalarmdotcom/alarmdotcom/assets/16128857/d0a7c38d-92be-4a1b-9c58-75f3478f2bef">


Do I need to change something on the website or somewhere else?

**Comment by farberm** [comment]
They all show not monitored on the website. Is that something that can be changed?

**Comment by elahd** [comment]
> Still cannot figure out why the malfunction and battery components are working but not the sensor.

That's an oversight. I'll release an update the cleans this up.

> They all show not monitored on the website. Is that something that can be changed?

Mine look the same. I'm not sure why Alarm.com does this.

**Comment by farberm** [comment]
I was hoping that this was the cause of my sensors being unavailable. i now have no idea why all the sensors are unavailable and show they are not monitored from the debug log. Do you have any other suggestions to try and remedy the issue?

**Comment by elahd** [comment]
I blocked those types of sensors from showing up in the most recent versions of the integration until I can get more detail regarding how they work / report state.

You're still seeing the devices because Home Assistant doesn't automatically delete them. Integration developers need to manually write device deletion code, and it's a tedious / dangerous operation. By dangerous, I mean that I need to be careful to not accidentally delete working devices. Not as easy as you'd think.

**Comment by farberm** [comment]
I must admit I do not fully understand the integration. Why would I want the sensor on my door or window that tells me whether it is open or closed to be deleted? I would prefer to have a notification that a door or window has been opened via a notification from HA and the status tracked. The website tracks the sensors as open or closed but for some reason this info is not being displayed on HA (its just displayed as unavailable). I am trying to determine if I have some problem with how I installed the integration or if its some other issue?

Thanks again for all your great work and I am sorry for my confusion and how things should be working

**Comment by elahd** [comment]
Sorry, I didn't realize that you were also talking about window and door sensors. I didn't remove window/door sensors -- I only removed smoke and CO sensors.

Can you delete your ADC config from Home Assistant, restart HA, then set up Alarm.com again? That will reset all of your sensor entities in HA. If you're still seeing issues, follow the single entity debug instructions [here](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#get-debug-data-for-a-single-entity) and report back.

Thanks!

**Comment by farberm** [comment]
I did that previosly and sent you the results above.....suf404 commented on them above.

**Comment by elahd** [comment]
Can you send debug data for a door/window sensor?

**Comment by farberm** [comment]
Back Doorr Sensor Debug


Logger: custom_components.alarmdotcom
Source: custom_components/alarmdotcom/__init__.py:156 
Integration: Alarm.com ([documentation](https://github.com/pyalarmdotcom/alarmdotcom), [issues](https://github.com/pyalarmdotcom/alarmdotcom/issues)) 
First occurred: 2:53:58 PM (1 occurrences) 
Last logged: 2:53:58 PM

ALARM.COM DEBUG DATA FOR BASEMENT BACK DOOR: {"deviceType": 1, "openClosedStatus": 2, "state": 0, "isFlexIO": false, "deviceRole": 0, "displayStateText": "Not Monitored", "isMonitoringEnabled": false, "sensorNamingFormat": 4, "supportsBypass": false, "supportsImmediateBypass": false, "isBypassed": false, "managedDeviceType": 12, "hasState": true, "canBeRenamed": true, "canBeDeleted": false, "canAccessWebSettings": true, "canAccessAppSettings": false, "webSettings": 400, "canAccessTroubleshootingWizard": false, "troubleshootingWizard": null, "addDeviceResource": 0, "canBeAssociatedToVideoDevice": true, "associatedCameraDeviceIds": {}, "macAddress": "", "manufacturer": "", "isAssignedToCareReceiver": false, "isOAuth": false, "isZWave": false, "supportsCommandClassBasic": false, "isMalfunctioning": false, "canBeSaved": true, "canChangeDescription": true, "description": "BASEMENT BACK DOOR", "deviceModelId": 110, "canConfirmStateChange": true, "canReceiveCommands": false, "remoteCommandsEnabled": true, "hasPermissionToChangeState": true, "deviceIcon": {"icon": 317}, "batteryLevelNull": null, "lowBattery": false, "criticalBattery": false}

**Comment by elahd** [comment]
Looping in @ZJGardner, who is running into the same issue with the same symptoms.

The problem is that your sensors are reporting `"state": 0` and `"isMonitoringEnabled": false`. A state of 0 means that the state is undefined. I think that Alarm.com returns state=0 when monitoring for a device is disabled. You should be able to confirm whether monitoring is enabled for a particular device at https://www.alarm.com/web/Security/Sensors.aspx:

![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/466460/ceafcbbd-dd0d-43d1-b073-2616b9c1bd1d)

Some devices (glass break, smoke, and CO, to name a few) will always show up on Alarm.com as not monitored, even though they are monitored. Contact sensors seem to be configurable.

A few questions:

1. Do you have a self-monitored Alarm.com plan? (That is, no call center.)
2. What brand/model sensor are you using?
3. Do you otherwise know why these sensors would be unmonitored?

For these sensors, I can change the code to use `openClosedStatus` instead of `state`, but I first want to get a sense of why your sensors are showing up the way they are.

**Comment by farberm** [comment]
1. No it is NOT self monitored. There is a call center - Security Central. However the alarm.com app sends me notifications when a sensor was left open so I was expecting is to report it to HA?
2. Alarm.com provider is Security Central
3. Alarm is a Interlogix NetworXs NX-8e and the associated sensors
4. The sensors are listed as unmonitored on the alarm.com website and there is not option that I see to change that. I have had no response from alarm.com as to why that is. But as I mentioned above I receive notifications when the sensor is let open.

**Comment by farberm** [comment]
I just got off the phone with the security people. They are going to see if they can turn on device monitoring option.. I will keep you updated.

**Comment by farberm** [comment]
I got the problem resolved....There were not sensors listed as a panel on the website. I called my alarm guy who went onto the website from his side and activated all my sensors to be monitored  - this was at no cost. Once he did that the sensors then showed up with a checkbox option for monitoring. Now they are are visible in HA. See below. Before they were listed as not monitored....So check with you alarm person thru the alrm.com website. Tehre should be a servie number there.
<img width="1021" alt="Screenshot 2023-06-12 at 7 28 22 PM" src="https://github.com/pyalarmdotcom/alarmdotcom/assets/16128857/7de16d3a-5819-43a1-be41-8e63930e3843">

**Comment by elahd** [comment]
Thanks for following up. Did your alarm guy say anything about the
difference between monitored and unmonitored? Presumably, your alarm would
trigger on these sensors even before this monitoring feature was turned on.

**Comment by farberm** [comment]
No he did not say anything about this. I think yes if the alarm is on then when the window is open it would sound the alarm unless it was bypassedSent from my iPhoneOn Jun 21, 2023, at 10:16 AM, Elahd Bar-Shai ***@***.***> wrote:﻿
Thanks for following up. Did your alarm guy say anything about the

difference between monitored and unmonitored? Presumably, your alarm would

trigger on these sensors even before this monitoring feature was turned on.
