### ISSUE TITLE
Reuse login device?

### ISSUE THREAD

**Issue by catellie** [pyalarmdotcom/alarmdotcom#248]
Although the integration now works fairly well (after issue 187 was resolved), there is one aspect that is somewhat annoying:
Each time I need to restart Home Assistant I receive a warning mail from my provider stating:

`Alert for Sign in from New Device`  ... `You're getting this email to make sure it was you. If you don't recognize this action, please reset your password immediately.`

Presumably the reason is that a device ID is randomly generated for each restart? Would it be possible to preserve this random ID between restarts so that this only shows up the first time (and/or when handshaking seriously freaks out)? I've not yet looked around the code to see where this happens, but if you can provide a pointer I'm happy to experiment - or perhaps this has already been tried and I should just not bother about it?

**Comment by elahd** [comment]
This has bugged me two. I originally thought that storing and reusing the 2FA token would prevent a new device from being created, but that's obviously not the case. If you're able to dig into how the website identifies itself on log in -- finding where the device is is stored -- that would be a huge help.

**Comment by catellie** [comment]
I've tried to look around a bit, but the stuff that is imported from `pyalarmdotcomajax` makes it tricky to add traces. Still, from just reading the code, my best guess for now is `deviceName`  for example [here](https://github.com/pyalarmdotcom/pyalarmdotcomajax/blob/master/pyalarmdotcomajax/__init__.py#L313)  - I would suggest tracing this value in the next release so that we can keep an eye on whether it changes each time there is a warning.
In my mind there is naming confusion around devices vs sensors and then this bug ugly Skybell hack in the middle doesn't really help :see_no_evil: 
The Alarm.com app talks about "Linked Devices" (which is the login sessions really), but also "Manage Devices" which are mostly sensors, but ALSO includes "Mobile Devices" where my phone is listed (same as under Recent Device Logins).
BTW: their reverse IP lookup is really useless - in my case it is off by 100 km...

**Comment by catellie** [comment]
For the record: this still keeps happening, but I can live with it - focus on the error handling refactor instead.
