### ISSUE TITLE
Adding additional systems to integration

### ISSUE THREAD

**Issue by Taralas** [pyalarmdotcom/alarmdotcom#251]
NOTE: Duplicate of closed issue: #174 

I am hoping there is a way to add more than 1 system to HA. Right now, I have an outbuilding and home added to my Alarm.com, which I can switch through via the UI on the site:

<img width="410" alt="Screenshot 2023-04-14 Home" src="https://user-images.githubusercontent.com/173816/232120333-8945e4cc-1fb9-47b3-977f-8dbea33f1a2c.png">
<img width="375" alt="Screenshot 2023-04-14 Outbuilding" src="https://user-images.githubusercontent.com/173816/232120338-5486e04c-45f0-4fd0-b786-a1cac5a8ae55.png">

What I would like to do would be have both systems accessible via the integration. I have followed the instructions at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#install-the-adc-command-line-tool. However, I am unable to sign in as my system supports 2FA, and even extracting the cookie and adding it to the commands do not allow a successful login to collect the raw JSON.

Happy to provide any support to get this working.

**Comment by Taralas** [comment]
Any chance either @elahd or @catellie would be interested in helping with this?

**Comment by catellie** [comment]
I'm not really sure how to help out with this as I only have one system to test with. My personal opinion would be to focus on getting the live listening properly working first - at least in my case the current polling approach typically gets confused after a week or so unless you either restart HA itself or reload the integration. Going for multiple systems before this is more stable is likely to be pretty confusing.

**Comment by Taralas** [comment]
At the moment, the single system is stable. @elahd had asked for the previous person requesting the enhancements to collect some data from their integration, and I would be happy to do so.

**Comment by elahd** [comment]
> At the moment, the single system is stable. @elahd had asked for the previous person requesting the enhancements to collect some data from their integration, and I would be happy to do so.

Are you able to post that info here?

**Comment by elahd** [comment]
Closing as stale. If anyone wants to open a ticket with the same request, please post the info that I requested above!
