### ISSUE TITLE
Two Factor Authentication Not Working

### ISSUE THREAD

**Issue by cconnoruk** [pyalarmdotcom/alarmdotcom#257]
When trying to run the inital setup I get the following error : Unknown error occurred

However I know the logon details are correct as if I get the password wrong the error changes and when I log into Alarm.com I can see the logins under linked devices, RECENT DEVICE LOGINS.

I don't get an MFA option, but I don't think that's the issue. Any assistance greatly received, thank you

**Comment by HazardousRat** [comment]
This is a 2FA issue. For testing purposes I disabled 2FA and HA added the integration once 2FA is enabled I get an "unknown error occurred" there is no option to input 2FA code.

**Comment by cconnoruk** [comment]
Tar, it's working with MFA off, I've had to leave it off though as it appears to break when I switch it back on again. All good, thank you.

**Comment by HazardousRat** [comment]
It's not all good. The integration is not working with MFA enabled as it was previously a few days ago. Can someone please look into this?

**Comment by sceccola** [comment]
I am having the same issue, however I do not have 2FA on alarm.com

**Comment by MervisDiamonds** [comment]
Same.

**Comment by smshapiro85** [comment]
FWIW I had 2FA on, tried to setup the integration, and received the same error. I disabled 2FA for now and it worked.

**Comment by elahd** [comment]
I have a fix for this, but it's tied in with other code that is not yet complete. For the time being, roll back to v2.2.0 or v2.1.0.

**Comment by mbhforum** [comment]
FWIW, the 2FA issue is not even letting me log in for v2.2.0 or 2.1.0 either.

**Comment by elahd** [comment]
Alarm.com changed their 2FA workflow again. I have a fix for the underlying library that I'm going to release as a beta this weekend. It'll be a few more days before I update the Home Assistant integration.

**Comment by elahd** [comment]
I've released an update to the underlying pyalarmdotcomajax library that powers this HA integration. This release fixes issues with 2FA, introduces a new method for refreshing device data, and supports real time notifications. My ability to test is limited -- it would be great if anyone here could help run some basic tests. See https://github.com/pyalarmdotcom/alarmdotcom/discussions/265 for testing details. Thanks!

**Comment by elahd** [comment]
I just released v3.0.0-beta of the integration with support for real time "push" updates and a fix for 2FA. 

If you don't see this version, go to HACS, click on integrations, click on Alarm.com, click on the 3 dot menu at the top right of the screen, click on redownload, and turn "show beta versions". v3 will appear shortly after turning this setting on.

**Comment by antonjs** [comment]
Perfect timing, since I just set up a new HA install and was hitting this issue (using Alarm.com to access ADT control). v3.0.0-beta lets me login, at least. Will let you know how the rest goes.

**Comment by elahd** [comment]
Thanks. Try v3.0.0-beta.2, as well.

**Comment by maniscalcojohn** [comment]
@elahd Thanks for your efforts to repair this. I am able to login with beta.2, but receiving the following error message:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmdotcom/controller.py:89
Integration: Alarm.com (documentation, issues)
First occurred: May 23, 2023 at 2:06:41 AM (1 occurrences)
Last logged: May 23, 2023 at 2:06:41 AM

Error setting up entry Advanced Security LLC:XXXXXXXXXXXXX@gmail.com for alarmdotcom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 65, in async_setup_entry
    await controller.initialize()
  File "/config/custom_components/alarmdotcom/controller.py", line 89, in initialize
    async_track_time_interval(
TypeError: async_track_time_interval() got an unexpected keyword argument 'name'

**Comment by elahd** [comment]
Can you update Home Assistant to a version >=2023.04? That error only shows up on "older" versions of HA.

**Comment by maniscalcojohn** [comment]
Oh boy. Ok. I am running 2023.3.3 (supervisor 2023.04.1) due to some breaking changes in 2023.4. I guess this will force me to fix that mess also.

**Comment by elahd** [comment]
I'm about to release another beta with a few bug fixes. I think that I can
make this compatible with older versions pretty easily.

**Comment by maniscalcojohn** [comment]
Working on beta.2 after updating to the latest version of HA... Thanks!!
