### ISSUE TITLE
Error setting up entry - Failed to set up 

### ISSUE THREAD

**Issue by tkilik11** [pyalarmdotcom/alarmdotcom#259]
Just started getting this error, I checked the logs on alarm.com and it seems to have logged in. 2fa disabled

Error setting up entry ADT Security 

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmdotcom/__init__.py:117 
Integration: Alarm.com (documentation, issues) 
First occurred: 9:50:24 AM (5 occurrences) 
Last logged: 6:49:03 PM

Error setting up entry ADT Security Australia:XXXXfor alarmdotcom
Error setting up entry ADT Security Australia:XXXX for alarmdotcom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 117, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by tkilik11** [comment]
any help would be great

**Comment by elahd** [comment]
Dupe of #257
