### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by thomasshawn** [pyalarmdotcom/alarmdotcom#270]
This was discussed a while back and I know there have much more pressing issues with stability but wanted to bump this back up for consideration once there's time.

Alarm.com app has scenes that are either predefined or custom. 

Would it be possible to access these scenes in some way vs recreating them somehow inside the HA environment?

**Comment by thomasshawn** [comment]
Checking on status of this one. Hoping to access the scenes that are setup in the webview/app

**Comment by elahd** [comment]
@thomasshawn This is now supported in v3.0.10.

**Comment by thomasshawn** [comment]
Awesome, traveling for another week, will test when I return.

**Comment by thomasshawn** [comment]
I had requested scenes. I see that it was implemented but I can't find them as an option. I still have the same choices I've always had, did I miss a checkbox somewhere to enable it?

**Comment by thomasshawn** [comment]
found them, i think, appears there's an open bug issue  [https://github.com/pyalarmdotcom/alarmdotcom/issues/345](url)
