### ISSUE TITLE
async_track_time_interval() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by scottwinaz** [pyalarmdotcom/alarmdotcom#274]
Running into the following error when attempting to configure the integration using 3.0.0-beta2.

Installation details:
HA - 2023.3.6
I am not using 2FA
Version 2.2.2 was working fine except for periodic "Error fetching data from Alarm.com"
Today, I fully deleted the integration from HA and HACS, then reinstalled it.  Still no luck.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmdotcom/controller.py:89
Integration: Alarm.com (documentation, issues)
First occurred: 10:05:47 AM (1 occurrences)
Last logged: 10:05:47 AM

```Error setting up entry Brinks Home™:<redacted> for alarmdotcom
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 65, in async_setup_entry
    await controller.initialize()
  File "/config/custom_components/alarmdotcom/controller.py", line 89, in initialize
    async_track_time_interval(
TypeError: async_track_time_interval() got an unexpected keyword argument 'name'```

**Comment by elahd** [comment]
You're seeing that error because you're using an older version of Home assistant. You need to be on 2023.04 or later. The "name" parameter in async_track_time_interval() is relatively new: https://github.com/home-assistant/core/commit/02ef7d445d8a723fe57712f37ca9c27595c5d1a2
