### ISSUE TITLE
Integration stops functioning

### ISSUE THREAD

**Issue by mashed2648** [pyalarmdotcom/alarmdotcom#277]
Hi all,

After working for several months, the alarm.com integration now suddenly stops sending commands or receiving state data several times per day. As far as the home assistant frontend or alarm.com itself, no errors or warnings are generated. Things just don't function until I reload the integration. I've done a fresh reinstall of the integration and updated HA to the latest version, neither made a difference. 

Is anyone else having this issue? Thanks.

**Comment by jkevinburton** [comment]
It's the exact issue I have.

**Comment by elahd** [comment]
Which version are you both using? There are a bunch of issues in the current stable release caused by changed to Alarm.com's API. Most are resolved (or are being resolved) in the current beta release.

**Comment by mashed2648** [comment]
Yeah I am using the most current stable release (2.2.2 I think). I'll give the newest beta a shot.

**Comment by jkevinburton** [comment]
Thanks, I'll try the beta

**Comment by elahd** [comment]
How are things looking? Also, v3.0.1 (stable) is out with some more fixes.

**Comment by jkevinburton** [comment]
So far so good with the beta2.
