### ISSUE TITLE
Cannot Get State or Set State of Alarm

### ISSUE THREAD

**Issue by mbhforum** [pyalarmdotcom/alarmdotcom#279]
I am running 3.0.0 Beta 2 that solved the MFA issue but I cannot get an accurate state or set the state of the alarm.  Log below. 

Logger: homeassistant.helpers.service
Source: helpers/service.py:757
First occurred: 10:01:52 AM (13 occurrences)
Last logged: 10:15:19 AM

Unable to find referenced entities alarm_control_panel.system or it is/they are currently not available

**Comment by elahd** [comment]
Can you try again with v3.0.1? If it still doesn't work, can you [turn on debug logging](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging) for the integration and post the websocket message that Home Assistant gets when you change the alarm state? Debug logging generates a ton of text, so you may have to dig for it. The logs you want look something like this:

```
====================[ WEBSOCKET MESSAGE: BEGIN ]====================
{
    "EventDateUtc": "2023-05-28T17:21:39.651Z",
    "UnitId": 103238342,
    "DeviceId": 1217,
    "EventType": 315,
    "EventValue": 255.0,
    "CorrelatedId": null,
    "QstringForExtraData": null,
    "DeviceType": -1
}
2023-05-28 17:21:39.919 DEBUG (MainThread) [pyalarmdotcomajax.websockets.messages] WebSocket Message Type: Event
2023-05-28 17:21:39.922 DEBUG (MainThread) [pyalarmdotcomajax.websockets.handler.light] Ignoring message. Already handled in separate status change message.
2023-05-28 17:21:39.922 DEBUG (MainThread) [pyalarmdotcomajax.websockets.client] 
====================[ WEBSOCKET MESSAGE: END ]====================
2023-05-28 17:21:39.924 DEBUG (MainThread) [pyalarmdotcomajax.websockets.client] 
====================[ WEBSOCKET MESSAGE: BEGIN ]====================
{
    "EventDateUtc": "2023-05-28T17:21:39.651Z",
    "UnitId": 103238342,
    "DeviceId": 1217,
    "NewState": 1,
    "FlagMask": 1
}
2023-05-28 17:21:39.924 DEBUG (MainThread) [pyalarmdotcomajax.websockets.messages] WebSocket Message Type: State Change
2023-05-28 17:21:39.924 INFO (MainThread) [pyalarmdotcomajax.devices] pyalarmdotcomajax.devices Got async update for Dining Room Light (103238342-1217) with new state: DeviceState.ON.
2023-05-28 17:21:39.925 INFO (MainThread) [custom_components.alarmdotcom.light] Processing state DeviceState.ON for Dining Room Light
2023-05-28 17:21:39.928 DEBUG (MainThread) [pyalarmdotcomajax.websockets.client] 
====================[ WEBSOCKET MESSAGE: END ]====================
```

**Comment by mbhforum** [comment]
Worked like a charm!  Thank you!

**Comment by mbhforum** [comment]
I actually might have spoken to soon, but it doesn't seem like it's working consistently for me.   A couple of issues:

1) Arm Home or Away works, but doesn't report the actual alarm state changing in a Dashboard. (see below. It looks like Alarm is in a Disarmed State, but it's not). 
2) Disarming doesn't work at all.  My guess is since the state isn't updated, it think it's already disarmed?

I turned on Debug Logging but am not seeing any log entries related to any activity. 

![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/11696289/ec0a84a5-0868-4a36-a687-40f8f507ca45)

**Comment by elahd** [comment]
Did you hit “View Full Logs” on the logs page? These logs won’t show up in
the default view.

**Comment by mbhforum** [comment]
I did. I am not finding anything in the logs which is strange.   If there is an easy way to search the logs for any keyword, let me know.

**Comment by jprasm** [comment]
Same issue here too.

**Comment by thomasshawn** [comment]
I guess I've been fortunate I have had no issues on this version

**Comment by elahd** [comment]
@mbhforum You can use the adc command line tool to view WebSocket messages. You can start a streaming session in a terminal, then arm/disarm the alarm from the Alarm.com website or app. You should see messages appear in the stream.

Follow the instructions [here](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#install-the-adc-command-line-tool) to install adc, then run the command `adc -d -u "YOURUSERNAME" -p "YOURPASSWORD" stream`

**Comment by mbhforum** [comment]
@elahd I was able to connect, but unfortunately everything I do in GUI Dashboard does not actually log anything in real time either. It almost appears it's a graphical issue where I click Home or Away and nothing registers.

**Comment by mbhforum** [comment]
Actually, I spoke too soon again.  The Status doesnt appear to update on the dashboard properly and the state is completely out of sync.

**Comment by elahd** [comment]
Test out v3.0.4-beta.1.

**Comment by elahd** [comment]
I'm closing this ticket to consolidate threads. Let's move this over to #288.
