### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by khs2424** [pyalarmdotcom/alarmdotcom#283]
Tried updating to 3.01 and it simply will not allow me to log back in. It only gives me the "Unknown error occurred" message. I've tried deleting integration and reinstalling it and it still gives the same error.

Had to go back to version 2.2.2 to finally get it to allow me to log back into Alarm.com.

**Comment by bfish2** [comment]
Having same issue here!

**Comment by jimmychanga** [comment]
Not to pile on, but I'm having the same issue since upgrading.

**Comment by Aipoc76** [comment]
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/42475106/8512ccc9-20e8-4299-97c0-08a1f86d8e8b)

**Comment by Aipoc76** [comment]
update.  a reconfigure and a reload got me in.

**Comment by Aipoc76** [comment]
I had 2FA on, I can not reconfigure it to ask for a 2FA access request again.  
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/42475106/9ff21876-b0af-4cc2-abaa-954552ad5d67)

**Comment by bfish2** [comment]
I added 2FA and now it is working again.  Only problem is I didn't want 2FA.  Oh, well.

**Comment by patrickabernathy** [comment]
I agree. I think this fixes it but since the documentation says 2FA is not required (says Maybe), perhaps this should be tagged a bug.

**Comment by elahd** [comment]
Sorry about that. It looks like Alarm.com rolled out changes to 2FA for just a subset of Alarm.com providers. Also, my provider now requires 2FA -- I thought that this applied to all Alarm.com users. Try v3.0.2. You should be able to login with 2FA now.
