### ISSUE TITLE
Smoke detectors no longer showing up in Alarm.com integration

### ISSUE THREAD

**Issue by Hex-Capital** [pyalarmdotcom/alarmdotcom#295]
I recently was prompted to add 2 factor authentication to my alarm.com integration. I upgraded my Alarm.com integration from 2.2.2 to 3.0.3 and reloaded... somehow all my smoke detectors were dropped from my Alarm.com device list and I can't find a way to add them back. I'm still able to see those devices on my account via the Alarm.com website

**Comment by elahd** [comment]
That's deliberate -- they're dropped for the time being. See Notifications #3 in https://github.com/pyalarmdotcom/alarmdotcom/releases/tag/v3.0.3. Also, I recommend upgrading to 3.0.4-beta.1. It's more stable than 3.0.3.
