### ISSUE TITLE
"Entity None (<class 'custom_components.alarmdotcom.binary_sensor.BinarySensor'>) is implicitly using device name by not setting its name" causes error "Cannot determine binary sensor state. Found raw state of DeviceState.UNKNOWN."

### ISSUE THREAD

**Issue by smshapiro85** [pyalarmdotcom/alarmdotcom#311]
Simply starting up HA results in this issue. On v3.0.4. No negative effects seem to arise out of this but the error message appears hundreds of times in the logs over a weeks period.

I enabled verbose logging, and it looks like the following log warning message precedes the actual error message, which then proceeds to occur many times over and over again:

`2023-07-13 13:08:27.290 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.alarmdotcom.binary_sensor.BinarySensor'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.`

`2023-07-13 13:08:27.292 ERROR (MainThread) [custom_components.alarmdotcom.binary_sensor] Cannot determine binary sensor state. Found raw state of DeviceState.UNKNOWN.`

`2023-07-13 13:08:27.297 ERROR (MainThread) [custom_components.alarmdotcom.binary_sensor] Cannot determine binary sensor state. Found raw state of DeviceState.UNKNOWN.`

**To Reproduce**
Shows immediately upon starting HA

**Screenshots**
<img width="1162" alt="image" src="https://github.com/pyalarmdotcom/alarmdotcom/assets/41717535/96983650-9c8d-4b8f-a0b1-6910a1dcd27e">

<img width="650" alt="image" src="https://github.com/pyalarmdotcom/alarmdotcom/assets/41717535/415013f6-dac7-495b-957d-692891268c15">

**Home Assistant Version:**
Alarm.com v. 3.0.4
Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Comment by yestrdave** [comment]
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/93943061/bb60acc3-b501-49ab-9f8c-f0e55127f15f)
Same Issue here. I have this error on two separate HA instance's 
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/93943061/ef1a5f1b-2be3-463d-bb57-9e007efccee7)
Alarm.com 3.0.4

**Comment by yestrdave** [comment]
This may help

Log Details (WARNING)
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:371
First occurred: 4:57:38 PM (5 occurrences)
Last logged: 4:57:38 PM

Entity None (<class 'custom_components.alarmdotcom.alarm_control_panel.AlarmControlPanel'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
Entity None (<class 'custom_components.alarmdotcom.binary_sensor.BinarySensor'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

**Comment by elahd** [comment]
Thanks! This is fixed via #314.

**Comment by yestrdave** [comment]
Issue is not resolved in Alarm.com v. 3.0.5
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/93943061/87911627-0c25-4740-8538-16df3815afe4)
