### ISSUE TITLE
Ignoring invalid device info Beta 2023.8.b0

### ISSUE THREAD

**Issue by o3aerialsolutions** [pyalarmdotcom/alarmdotcom#314]
Please provide as much detail as possible. It's helpful to include Home Assistant debug logs from this integration. Instructions for enabling debugging are available at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging. (Alarmdotcom debug logs are verbose, so don't forget to disable debug logging when you're done!)

**Describe the bug**
Ignoring invalid device info: Invalid device info {'default_manufacturer': 'Alarm.com', 'default_name': 'Bedroom Window', 'identifiers': {('alarmdotcom', 'XXXXXXXX-15')}, 'via_device': ('alarmdotcom', 'XXXXXXXX-127')} for 'alarmdotcom' config entry: device info needs to either describe a device, link to existing device or provide extra information.

All devices go unavailable

**To Reproduce**
Steps to reproduce the behavior: Install Beta

**Expected behavior**

**Screenshots**

**Home Assistant Version:**

**Additional context**

**Comment by o3aerialsolutions** [comment]
V2.2.3 fixed it.  Thank you !!!

**Comment by o3aerialsolutions** [comment]
closed as fixed

**Comment by elahd** [comment]
Fixed in v0.3.5, as well.
