### ISSUE TITLE
Double Device Names For Entity

### ISSUE THREAD

**Issue by Lurick73** [pyalarmdotcom/alarmdotcom#316]
**Describe the bug**
I noticed after the latest update that all Alarm.com Z-Wave devices now show in Home Assistant with their names twice for the device name. Example: Living Room Light now shows as light.Living Room Light Living Room Light
What's odd is that when I go do the Devices list in Home Assistant the names show correct (IE: once) so the entity ID isn't changed just what shows in the cards on the dashboard

**To Reproduce**

1. Link device to alarm.com
2. Add z-wave device
3. View device name
4. Add device to dashboard in a card and see that device name shows twice for Entity (but not entity ID) as well
5. See error on card display name

**Expected behavior**
Should show device name only once for Entity.

**Screenshots**
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/62802459/9bf0f252-f307-4ac4-bbff-82cdec4d6024)

**Home Assistant Version:**
Home Assistant 2023.7.3
Frontend 20230705.1 - latest 

**Additional context**
Workaround is to manually put in the name to overwrite the default display.

**Comment by Lurick73** [comment]
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/62802459/009a72b8-1b02-47fa-a997-3fa9063b6810)

**Comment by elahd** [comment]
This is fixed in [v3.0.7](https://github.com/pyalarmdotcom/alarmdotcom/releases/tag/v3.0.7). Can you update and confirm?

**Comment by Lurick73** [comment]
> This is fixed in [v3.0.7](https://github.com/pyalarmdotcom/alarmdotcom/releases/tag/v3.0.7). Can you update and confirm?

Yup, I can confirm
