### ISSUE TITLE
Integration becomes unavailable and needs to be reloaded to fix issue

### ISSUE THREAD

**Issue by sceccola** [pyalarmdotcom/alarmdotcom#321]
About once every 24 hours, my integration becomes unavailable.   Reloaded fixes issue

**Comment by bkr1969** [comment]
Mine is not becoming unavailable, but it is taking 20-30 seconds to update the status.

**Comment by Raul-7-7** [comment]
in my experience, it takes about 2-3 min to update at times, sometimes 10-15 seconds! 

you also might want to take a look at here: https://github.com/pyalarmdotcom/alarmdotcom/issues/288

**Comment by elahd** [comment]
@sceccola If you can provide relevant logs from Home Assistant, reopen the ticket and I'll take a look.
