### ISSUE TITLE
Cannot determine light state. Found raw state of DeviceState.NOSTATE

### ISSUE THREAD

**Issue by GTerplan** [pyalarmdotcom/alarmdotcom#325]
Constant error in HA logs.

**Describe the bug**
This error originated from a custom integration.

Logger: custom_components.alarmdotcom.light
Source: /config/custom_components/alarmdotcom/light.py:83
Integration: Alarm.com (documentation, issues)
First occurred: August 24, 2023 at 6:54:09 PM (43806 occurrences)
Last logged: 10:38:21 PM

Cannot determine light state. Found raw state of DeviceState.NOSTATE.
NoneType: None

**Home Assistant Version:**
Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.0
Frontend 20230802.1 - latest

**Additional context**
This seems to be slowing down HA in general since it's logging constantly.

**Comment by elahd** [comment]
What state shows up for the light on Alarm.com when this error pops up? Are you able to provide debug output for this device using the "Raw JSON" instructions at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#install-the-adc-command-line-tool?

**Comment by elahd** [comment]
This should be fixed in v3.0.8.
