### ISSUE TITLE
v3.0.10 broke integration?

### ISSUE THREAD

**Issue by Whaledad** [pyalarmdotcom/alarmdotcom#340]
Please provide as much detail as possible. It's helpful to include Home Assistant debug logs from this integration. Instructions for enabling debugging are available at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging. (Alarmdotcom debug logs are verbose, so don't forget to disable debug logging when you're done!)

**Describe the bug**
I just upgraded vrom 3.0.6 to 3.0.10 and the entire integration seems to be broken. All entities are unavailable.

**To Reproduce**

1. Update to 3.0.10
2. Click on Entities
3. All entities show unavaialble

**Expected behavior**
Expect all entities to show up and function

**Screenshots**

**Home Assistant Version:**
Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1 (Pi)
Frontend 20231005.0 - latest

**Additional c
![Screenshot 2023-10-27 120707](https://github.com/pyalarmdotcom/alarmdotcom/assets/35144341/13402ca0-e290-4abb-9ddf-d56c877d8c03)
**Additional context**
![Screenshot 2023-10-27 121027](https://github.com/pyalarmdotcom/alarmdotcom/assets/35144341/01e40d7d-7c65-4d36-85db-34dbf7d0846a)
The "21 minutes ago" in the second screenshot refers to the exact time of the upgrade.

**Comment by elahd** [comment]
Try going back to HACS -> Integrations -> Alarm.com. Click on the `⋮` menu on the top right, then click "Redownload". When that's done, reboot and try again.

**Comment by Whaledad** [comment]
> Try going back to HACS -> Integrations -> Alarm.com. Click on the `⋮` menu on the top right, then click "Redownload". When that's done, reboot and try again.

That worked! Thanks!
