### ISSUE TITLE
Unable to install update 3.0.11

### ISSUE THREAD

**Issue by bkr1969** [pyalarmdotcom/alarmdotcom#352]
Please provide as much detail as possible. It's helpful to include Home Assistant debug logs from this integration. Instructions for enabling debugging are available at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging. (Alarmdotcom debug logs are verbose, so don't forget to disable debug logging when you're done!)

**Describe the bug**

**To Reproduce**
Try to install update

**Expected behavior**
If I get a notification of an update it should install

**Screenshots**
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/42385989/4feab54f-ab2f-4f61-b936-1baa4dbf639d)

![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/42385989/f2327fb6-bf91-42d8-a683-857940332d67)

**Home Assistant Version:**

**Additional context**

**Comment by cfpandrade** [comment]
I have the same issue, waiting for a resolution :(

**Comment by eliasisrael** [comment]
Me too

**Comment by sargonas** [comment]
same issue. Manually installing 3.0.11 results in reporting 3.0.10 upon reboot as well.

**Comment by elahd** [comment]
Updating should be fixed in v3.0.12.
