### ISSUE TITLE
Forced Migration to Service Provider Website

### ISSUE THREAD

**Issue by ghds514** [pyalarmdotcom/alarmdotcom#357]
Hello, appreciate the work on this and I had come to depend on it as part of my Home Assistant dashboard and for some automations. 

Not sure if this qualifies as a bug, but I have lost access to this integration because my service provider (Telus in Canada) has forced migration of login credentials from the original alarm.com to their login on their site. The result is that I no longer have access to the alarm.com site at all but instead have access to a clone of the alarm.com system on a different domain (https://smarthome-security.telus.com/). I am assuming this was a branding exercise by some marketing genius.

Is there any way to modify the domain that the integration accesses in order to try to regain access to my account on Home Assistant?

**Comment by Raul-7-7** [comment]
Oh shoot @ghds514 I am also with Telus but not yet forced to move (i get the msg every time I login but ignore it) , how did they force you? no longer able to login?

as for the issue, since the UI is the same, I am hoping this to be less complex to support.

**Comment by ghds514** [comment]
I have my cell phones there and there was a link to the Home Security login on the main dashboard they offer. There, it said migration of credentials was necessary to access the Home Security features and there was a message that the legacy alarm.com credentials would soon be no longer accessible. I did not fully think through what it was forcing and as soon as the migration was done, the alarm.com app and web site were not longer accessible (i.e., my original login credentials were erased in the process). Of course, this integration stopped working as well. You are forced to use Telus apps and web pages which are direct clones (white label if you wish). 

The integration correctly reports it as Telus Home Security but it cannot login. I have been amateurishly perusing the code for the integration in the hopes of finding reference to a URL that I can change to make this work again. Also considering moving to other providers who do not have this "feature" but that may entail buying a new panel and at least some of the sensors.

I also believe there may be a simple solution since Telus' system is a simple clone of Alarm.com. I believe there are numerous security service providers that do this; I see at least one more locally, which suggests there may be many internationally. Being able to change the "domain" through a configuration entry in the integration may be a way to accommodate these situations.

**Comment by Raul-7-7** [comment]
@ghds514 wild idea, what if you add a custom DNS entry to point alarm.com to Telus ? I am 99% sure you are going to run into Certificate issue but worth trying? i am still using alarm.com so can not try this. Also I am curious if you open the network tab on Chrome while on the new Telus site, the API calls the site is making is it to alarm.com or telus?

**Comment by ghds514** [comment]
Difficulty is that alarm.com no longer recognizes any of my login credentials, neither the original alarm.com nor the new Telus ones, so a simple redirect is unlikely to work. I will see if I can figure out who the Telus site is communicating with, I suspect it is in fact alarm.com's servers but will try to confirm.

**Comment by ghds514** [comment]
Cancelled Telus' service and moved to a provider that offers a direct alarm.com integration as opposed to a proprietary login. Telus reps admitted they have received complaints about this since last April but do not seem to be budging on this policy/marketing-effort. The integration is now working better than ever.

**Comment by dwdblogger** [comment]
following - I have the same issue except that I was legacy ADT Canada customer which then Telus tookover. Then cancelled for a year and now as a new Telus Canada Security customer it's defaulted to the setup at https://smarthome-security.telus.com/) - @ghds514 It's a shot in the dark but if it can be somehow redirected to this new login URL the credentials you could use are your telus account creds.

**Comment by dwdblogger** [comment]
> A new development is that I started getting emails from Telus with failed login notices when I tried to configure the integration. This means that communication with alarm.com servers was likely occurring. A call to Telus about this offered no help.
> 
> I finally cancelled Telus' service and moved to a provider that offers a direct alarm.com integration as opposed to a proprietary login. Telus reps admitted they have received complaints about this since last April but do not seem to be budging on this policy/marketing-effort. The integration is now working better than ever.
> 
> Admins may wish to close this issue.

I missed your last post somehow - which provider did you end up switching to?

**Comment by dwdblogger** [comment]
thx, that's helpful. curious did you have cameras as part of the telus setup and were you able to transition those to Taz also?

**Comment by ghds514** [comment]
I did not have cameras integrated through Telus, but this was a question posed to me by Taz and all other providers. I believe they would all have been able to migrate those over.
