### ISSUE TITLE
scenes?

### ISSUE THREAD

**Issue by thomasshawn** [pyalarmdotcom/alarmdotcom#359]
I know we briefly had scenes and then we lost them
are we any closer to getting them back. i'm on 3.0.11 (3.0.10 works better for me though) but checked just to see if scenes werew back.

thanks for continuing to work on this

**Comment by elahd** [comment]
v3.0.12 fully kills the feature for now -- sorry! I'm working on a new major release -- and code refactor -- that will include scene support. Stay tuned...

**Comment by thomasshawn** [comment]
thank you
