### ISSUE TITLE
Use of TEMP_CELSIUS and TEMP_FAHRENHEIT deprecated in  HA Core 2025.1

### ISSUE THREAD

**Issue by pdobrien3** [pyalarmdotcom/alarmdotcom#361]
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 7:43:17 AM (2 occurrences)
Last logged: 7:43:17 AM

TEMP_CELSIUS was used from alarmdotcom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/pyalarmdotcom/alarmdotcom/issues
TEMP_FAHRENHEIT was used from alarmdotcom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/pyalarmdotcom/alarmdotcom/issues

**Home Assistant Version:**
2024.1.0b2

**Comment by elahd** [comment]
This is fixed in v3.0.12.
