### ISSUE TITLE
Automatically created binary_sensor entities are sometimes missing the "SHOW AS" field

### ISSUE THREAD

**Issue by rmatte** [pyalarmdotcom/alarmdotcom#96]
Automatically created binary_sensor entities are sometimes missing the "SHOW AS" field.  I noticed this happen only for window sensors for me, though not for all of my window sensors for whatever reason.

When this happens the icon for those sensors doesn't get set to a window icon automatically (it gets set to some circle icon) and the text shows as Off / On instead of Open /  Closed and there's no way to manually change that after the fact apparently as there's no way to add in the "show as" field to an entity if it's missing (at least no way that I could find).

This throws off my list of entity states that I have on one of my dashboards where some show Closed, others show Off.  It would be nice if this could be fixed to at least force the "show as" field to be there no matter what (default it to the "Other" value if needed) so that we could at least correct this by hand if it happens.

I'd also recommend just searching for the word "window" in a case-insensitive way and make sure that it's always setting the "show as" field to window based on that.  Right now it seems to be hit or miss for whatever reason, though it did appear to work for all of my door sensors, so I'm not sure why it's so flaky when it came to the window sensors.

**Comment by elahd** [comment]
> I'd also recommend just searching for the word "window" in a case-insensitive way and make sure that it's always setting the "show as" field to window based on that.

That's how the integration works. The language dictionary is in  [custom_components/alarmdotcom/device_type_langs.py](https://github.com/uvjustin/alarmdotcom/blob/master/custom_components/alarmdotcom/device_type_langs.py) and the logic is below, from [custom_components/alarmdotcom/binary_sensor.py](https://github.com/uvjustin/alarmdotcom/blob/master/custom_components/alarmdotcom/binary_sensor.py).

https://github.com/uvjustin/alarmdotcom/blob/b4aeeea14bab22c67643726b3681c3ad96e8cec4/custom_components/alarmdotcom/binary_sensor.py#L72-L96

If the sensor doesn't find the word "door" or "window" in the sensor name, it'll default to a generic binary sensor.

Can you post the names of some of the window sensors that aren't being picked up correctly?

**Comment by elahd** [comment]
Also, would you be able to post the config entry for one of those windows? The entry is in /config/.storage/core.entity_registry. It looks like this:

```json
            {
                "area_id": null,
                "capabilities": null,
                "config_entry_id": "6e829f4843eac5bd512858c23627ff03",
                "device_class": null,
                "device_id": "8426ff6a27f8159d35de638f535caf94",
                "disabled_by": null,
                "entity_category": null,
                "entity_id": "binary_sensor.kitchen_window_four",
                "icon": null,
                "id": "280e039f49da96ec64072fd2119a7339",
                "name": null,
                "options": {},
                "original_device_class": "window",
                "original_icon": null,
                "original_name": "Kitchen Window Four",
                "platform": "alarmdotcom",
                "supported_features": 0,
                "unique_id": "XXXXXXXX",
                "unit_of_measurement": null
            },
```
Be sure to block out the "unique_id" field as that contains an ID from your Alarm.com account.

I have a feeling that the "Show as" bug lives in the HA frontend and basically just fails to show up for binary sensors with the default device class. "Show as" is a new feature. See https://github.com/home-assistant/frontend/issues/11916 for a similar bug report.

**Comment by rmatte** [comment]
I rolled back to the old version of this because of https://github.com/uvjustin/alarmdotcom/issues/95 but I'll find some time soon to temporarily re-upgrade it to get you that info.  Many of them definitely did have "window" in the sensor name and didn't get detected as windows.  I'll get that info to you in here as soon as I can (I'll probably have some time to tomorrow).

**Comment by rmatte** [comment]
Now that #95 is fixed I'm in the process of re-testing this.  You can see the names of several of my window sensors here which don't have a "SHOW AS" field set on them.  I'm going to grab the config info for one of them that you asked for previously and posted it here in a minute.  [https://i.imgur.com/KUrWsuE.png](url)

**Comment by rmatte** [comment]
Here is another example which shows how all of my door sensors got the SHOW AS field created and set properly on them while only some of my window sensors did: https://i.imgur.com/fXdnBSG.png

Not sure why that is.  Checking the config data you asked for next...

**Comment by rmatte** [comment]
Here's an example from one of the sensors where that isn't getting set properly on it despite containing the word "window" in it's name...

`            {
                "area_id": null,
                "capabilities": null,
                "config_entry_id": "a14c6458be0e4dcbbb360478767d30ae",
                "device_class": null,
                "device_id": "453fc0fd8a7405b94d94eeabd9cbb8e3",
                "disabled_by": null,
                "entity_category": null,
                "entity_id": "binary_sensor.garage_window",
                "icon": null,
                "id": "35aebffe18f729252f3c77706a704f77",
                "name": null,
                "options": {},
                "original_device_class": null,
                "original_icon": null,
                "original_name": "Garage Window",
                "platform": "alarmdotcom",
                "supported_features": 0,
                "unique_id": "SENSORED",
                "unit_of_measurement": null
            },`
            
Let me know if you need anything else.  I'll dig in to the code a bit myself and see what I can find.

**Comment by rmatte** [comment]
I'm heading out for a bit but I'll dig in to this more when I get back.

**Comment by rmatte** [comment]
Here is the one that got detected properly...

```
            {
                "area_id": null,
                "capabilities": null,
                "config_entry_id": "a14c6458be0e4dcbbb360478767d30ae",
                "device_class": null,
                "device_id": "4298a2245e420dff79c69f01e65fb93c",
                "disabled_by": null,
                "entity_category": null,
                "entity_id": "binary_sensor.diningroom_window_1",
                "icon": null,
                "id": "30ada0220f6eabd82bc288533f5e9f23",
                "name": null,
                "options": {},
                "original_device_class": "window",
                "original_icon": null,
                "original_name": "Diningroom Window 1",
                "platform": "alarmdotcom",
                "supported_features": 0,
                "unique_id": "SENSORED",
                "unit_of_measurement": null
            },
```

**Comment by rmatte** [comment]
I'm not noticing any kind of pattern in the naming that could account for one being detected vs one not being.  For instance "Diningroom Window 1" and "Diningroom Window 2" got detected as windows, but "Kitchen Window 1" and "Kitchen Window 2" did not.  There's something weird going on here.

**Comment by rmatte** [comment]
I think I see the problem in the code.  It's this line in binary_sensor.py...

```
        if self._device_subtype_raw == ADCSensorSubtype.CONTACT_SENSOR:
```

Just above where it's doing the regex matching to see if it's a door or window sensor.  That's assuming it's going to be a CONTACT_SENSOR but all of mine that aren't being set as window sensors properly are probably not being detected as "CONTACT_SENSOR" because they are also glass break sensors (shock sensors) so they probably have some different type.  Because that if statement is only specifically doing the matching for that against CONTACT_SENSOR my open/close sensors which also double as shock sensors are being totally excluded.  I just need to figure out what type these are detected as and modify that if statement to account for these to get this working.  I'll let you know once I figure it out.

**Comment by rmatte** [comment]
So it looks like you're using some hardcoded index of device types from the pyalarmdotcomajax package...

```
class ADCSensorSubtype(IntEnum):
    """Library of identified ADC device types."""

    CONTACT_SENSOR = 1
    MOTION_SENSOR = 2
    SMOKE_DETECTOR = 5
    CO_DETECTOR = 6
    PANIC_BUTTON = 9
    GLASS_BREAK_DETECTOR = 19
    PANEL_MOTION_SENSOR = 89
```
Either these sensors are some new type that's not in there or it's in there and just needs to be added to that if statement.  I'm working to figure out which.

**Comment by rmatte** [comment]
I'm just trying to get it to spit out the integer representing the sensor type right now via logging but I'm running in to some weirdness, keep getting errors like this even when I put the code back to the way it was before I started...

```
2022-04-03 16:07:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in async_add_entities
    tasks = [
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in <listcomp>
    tasks = [
  File "/config/custom_components/alarmdotcom/binary_sensor.py", line 39, in <genexpr>
    ADCIBinarySensor(controller, controller.devices.get("entity_data", {}).get(sensor_id))  # type: ignore
  File "/config/custom_components/alarmdotcom/binary_sensor.py", line 76, in __init__
    if self._device_subtype_raw == ADCSensorSubtype.CONTACT_SENSOR:
TypeError: not enough arguments for format string
```
I'm restarting HA to see if it fixes this or not.

**Comment by rmatte** [comment]
Ok, so the restart fixed it.  I'm basically just modifying some of the debug logging to try to get it to spit out the raw integer value for the device type for these.  I can see that with the standard functions being used to pull it it's just returning None.

**Comment by rmatte** [comment]
To work around this for now I edited binary_sensor.py and changed...

```
if self._device_subtype_raw == ADCSensorSubtype.CONTACT_SENSOR:
```
to...

```
if self._device_subtype_raw == ADCSensorSubtype.CONTACT_SENSOR or self._device_subtype_raw == None:
```
and added...

```
        elif self._device_subtype_raw == None:
            return self._derived_class
```
directly below...

```
        if (
            self._derived_class is not None
            and self._device_subtype_raw == ADCSensorSubtype.CONTACT_SENSOR
        ):
            return self._derived_class
```
It's a crude workaround but it works.  I could keep digging to try to figure out what the integer is that represents the types of these sensors, but I really think this code needs to become less hard coded and more generic for this stuff.  Either consider making the code changes that I made or give me steps to get the sensor info from my sensors that you need to fix this in the code.  Whichever you prefer.  At least I have a workaround for now though it would be great to see an official fix implemented.

Let me know what you need from me for this to fix this, if anything.

Thanks.

**Comment by elahd** [comment]
Thanks for digging into this. The pyalarmdotcomajax python module includes a CLI that can dump Alarm.com debug info. You can install it on your daily driver using pip. The condensed instructions for this are:

1) [Install pip](https://pip.pypa.io/en/stable/installation/#). 
2) Use pip to install pyalarmdotcomajax: `pip install pyalarmdotcomajax`.
3) Use the pyalarmdotcomajax command line tool to dump raw sensor data: `adc -u YOUR_USERNAME -p YOUR_PASSWORD -c YOUR_2FA_COOKIE -vx`

The tool will dump all of your sensor data formatted as JSON. You'll see sensor type IDs listed in the output. Use a [JSON prettifier](https://jsonprettier.com/) to help.

Let me know if you need any more info to try this.

**Comment by rmatte** [comment]
> Thanks for digging into this. The pyalarmdotcomajax python module includes a CLI that can dump Alarm.com debug info. You can install it on your daily driver using pip. The condensed instructions for this are:
> 
> 1. [Install pip](https://pip.pypa.io/en/stable/installation/#).
> 2. Use pip to install pyalarmdotcomajax: `pip install pyalarmdotcomajax`.
> 3. Use the pyalarmdotcomajax command line tool to dump raw sensor data: `adc -u YOUR_USERNAME -p YOUR_PASSWORD -c YOUR_2FA_COOKIE -vx`
> 
> The tool will dump all of your sensor data formatted as JSON. You'll see sensor type IDs listed in the output. Use a [JSON prettifier](https://jsonprettier.com/) to help.
> 
> Let me know if you need any more info to try this.

I tried installing pyalarmdotcomajax from pip but it's some ancient version and there is no "adc" command once it's installed.  Then I tried just cloning the latest version and installing it but then when I try to run adc with the proper options (had to use "-v get -x" instead of "-vx" like you had said) it bombs out like this...

```
Traceback (most recent call last):
  File "/usr/local/bin/adc", line 11, in <module>
    load_entry_point('pyalarmdotcomajax==0.3.1', 'console_scripts', 'adc')()
  File "/usr/local/lib/python3.8/dist-packages/pyalarmdotcomajax-0.3.1-py3.8.egg/pyalarmdotcomajax/cli.py", line 596, in main
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/pyalarmdotcomajax-0.3.1-py3.8.egg/pyalarmdotcomajax/cli.py", line 293, in cli
  File "/usr/local/lib/python3.8/dist-packages/pyalarmdotcomajax-0.3.1-py3.8.egg/pyalarmdotcomajax/cli.py", line 446, in _async_machine_output
  File "/usr/local/lib/python3.8/dist-packages/pyalarmdotcomajax-0.3.1-py3.8.egg/pyalarmdotcomajax/__init__.py", line 455, in async_get_raw_server_responses
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

So so far no luck with debugging this.  I'm going to see if I can get some other versions of this working.

**Comment by rmatte** [comment]
I just managed to get it working by installing version 0.2.10 of the pyalarmdotcomajax package.  I've got the data dumped so I'm going to analyze it and then follow up with more info.

**Comment by rmatte** [comment]
Ok, so after dumping the data I can see that for these open/close (contact) window sensors which double as glass break / shock sensors, the device type is 52 and the deviceModelId shows up as 717.  So I'm thinking we need something like this...

```
class ADCSensorSubtype(IntEnum):
    """Library of identified ADC device types."""

    CONTACT_SENSOR = 1
    MOTION_SENSOR = 2
    SMOKE_DETECTOR = 5
    CO_DETECTOR = 6
    PANIC_BUTTON = 9
    GLASS_BREAK_DETECTOR = 19
    CONTACT_SHOCK_SENSOR = 52
    PANEL_MOTION_SENSOR = 89
````
Then adjust the if statements I mentioned 5 notes back to use that new type entry.  I'm going to try it in the code for myself to confirm that it works.

**Comment by rmatte** [comment]
It looks like it's not easy for me to get access to actually edit the pyalarmdotcomajax package on HASS so I'm going to just wait for you guys to hopefully add this in in a future release and just continue using my workaround for now.

**Comment by rmatte** [comment]
> Thanks for digging into this. The pyalarmdotcomajax python module includes a CLI that can dump Alarm.com debug info. You can install it on your daily driver using pip. The condensed instructions for this are:
> 
> 1. [Install pip](https://pip.pypa.io/en/stable/installation/#).
> 2. Use pip to install pyalarmdotcomajax: `pip install pyalarmdotcomajax`.
> 3. Use the pyalarmdotcomajax command line tool to dump raw sensor data: `adc -u YOUR_USERNAME -p YOUR_PASSWORD -c YOUR_2FA_COOKIE -vx`
> 
> The tool will dump all of your sensor data formatted as JSON. You'll see sensor type IDs listed in the output. Use a [JSON prettifier](https://jsonprettier.com/) to help.
> 
> Let me know if you need any more info to try this.

See above for debug details.  Please include this new device type along with a fix for those if statements so that it considers that device type as a contact sensor as well.  I'm sure there are plenty of people out there who are using these contact/shock combo sensors.  Thanks.

**Comment by elahd** [comment]
Added to v0.2.10. Can you update and confirm that this works for you?

**Comment by rmatte** [comment]
Just updated, will test and follow up.
